name: andina_rrhh
description: "App móvil Andina RR. HH. — asistencia, permisos y notificaciones."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.5.5
  provider: ^6.1.5+1
  intl: ^0.20.3
  google_fonts: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
