-- =============================================================================
-- Instalación completa de rrhh_andina: esquema + datos iniciales.
-- PostgreSQL 16+. Origen: Plan de Toma de Requerimientos v1.0 (Agosto 2026).
--
-- pgAdmin:
--   1. 00_create_database.sql   Query Tool sobre "postgres" (Auto commit)
--   2. 01_install.sql           Query Tool sobre "rrhh_andina", F5
--   3. 02_reset.sql             Solo si quieres volver a dejar 3 cuentas limpias
--
-- Este archivo se puede repetir: borra el esquema public y lo recrea.
-- Contraseña de las 3 cuentas: Andina2026. Guía: docs/PRUEBAS.md
-- =============================================================================

DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;
GRANT ALL ON SCHEMA public TO CURRENT_USER;
GRANT ALL ON SCHEMA public TO public;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- -----------------------------------------------------------------------------
-- Tipos enumerados
-- -----------------------------------------------------------------------------
CREATE TYPE tipo_documento AS ENUM ('DNI', 'CE', 'PASAPORTE');
CREATE TYPE sexo_empleado AS ENUM ('M', 'F');
CREATE TYPE tipo_contrato AS ENUM ('PLANILLA', 'RECIBO_HONORARIOS', 'PRACTICAS');
CREATE TYPE estado_empleado AS ENUM ('ACTIVO', 'INACTIVO', 'CESADO');
CREATE TYPE tipo_marcacion AS ENUM ('INGRESO', 'SALIDA');
CREATE TYPE estado_solicitud AS ENUM ('PENDIENTE', 'APROBADO', 'RECHAZADO', 'CANCELADO');
CREATE TYPE accion_solicitud AS ENUM (
    'REGISTRAR',
    'ENVIAR_APROBACION',
    'APROBAR',
    'RECHAZAR',
    'CANCELAR',
    'ACTUALIZAR'
);
CREATE TYPE estado_carga AS ENUM ('PROCESANDO', 'COMPLETADA', 'COMPLETADA_CON_ERRORES', 'FALLIDA');
CREATE TYPE resultado_fila_carga AS ENUM ('INSERTADO', 'ACTUALIZADO', 'ERROR');
CREATE TYPE formato_reporte AS ENUM ('EXCEL', 'PDF');
CREATE TYPE tipo_reporte AS ENUM (
    'TRABAJADORES',
    'PERMISOS',
    'HORAS_EXTRAS',
    'ASISTENCIA',
    'USUARIOS'
);
CREATE TYPE tipo_origen_flujo AS ENUM ('PERMISO', 'HORA_EXTRA');
CREATE TYPE tipo_aprobador AS ENUM ('JEFE_INMEDIATO', 'ROL', 'USUARIO');
CREATE TYPE estado_paso_aprobacion AS ENUM (
    'PENDIENTE',
    'EN_CURSO',
    'APROBADO',
    'RECHAZADO',
    'OMITIDO',
    'CANCELADO'
);

-- -----------------------------------------------------------------------------
-- Catálogos organizacionales (SS-01)
-- -----------------------------------------------------------------------------
CREATE TABLE area (
    id_area         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(80) NOT NULL,
    descripcion     VARCHAR(250),
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_area_nombre UNIQUE (nombre)
);

CREATE TABLE cargo (
    id_cargo        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(80) NOT NULL,
    descripcion     VARCHAR(250),
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_cargo_nombre UNIQUE (nombre)
);

CREATE TABLE horario_laboral (
    id_horario      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(80) NOT NULL,
    hora_ingreso    TIME NOT NULL,
    hora_salida     TIME NOT NULL,
    minutos_refrigerio INTEGER NOT NULL DEFAULT 60,
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_horario_nombre UNIQUE (nombre),
    CONSTRAINT ck_horario_rango CHECK (hora_salida > hora_ingreso),
    CONSTRAINT ck_horario_refrigerio CHECK (minutos_refrigerio BETWEEN 0 AND 180)
);

CREATE TABLE tipo_permiso (
    id_tipo_permiso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(30) NOT NULL,
    nombre          VARCHAR(80) NOT NULL,
    requiere_sustento BOOLEAN NOT NULL DEFAULT FALSE,
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_tipo_permiso_codigo UNIQUE (codigo),
    CONSTRAINT uq_tipo_permiso_nombre UNIQUE (nombre)
);

CREATE TABLE parametro_sistema (
    clave           VARCHAR(80) PRIMARY KEY,
    valor           VARCHAR(200) NOT NULL,
    descripcion     VARCHAR(300),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- Usuarios, roles y permisos (SS-05, RI-05, RG-02, RG-13)
-- -----------------------------------------------------------------------------
CREATE TABLE rol (
    id_rol          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(30) NOT NULL,
    nombre          VARCHAR(80) NOT NULL,
    descripcion     VARCHAR(250),
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_rol_codigo UNIQUE (codigo)
);

CREATE TABLE permiso_funcional (
    id_permiso      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(60) NOT NULL,
    nombre          VARCHAR(120) NOT NULL,
    modulo          VARCHAR(40) NOT NULL,
    descripcion     VARCHAR(250),
    CONSTRAINT uq_permiso_funcional_codigo UNIQUE (codigo)
);

CREATE TABLE rol_permiso (
    id_rol          INTEGER NOT NULL REFERENCES rol (id_rol) ON DELETE CASCADE,
    id_permiso      INTEGER NOT NULL REFERENCES permiso_funcional (id_permiso) ON DELETE CASCADE,
    fecha_asignacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id_rol, id_permiso)
);

-- Menú dinámico por perfil (rol)
CREATE TABLE menu_item (
    id_menu         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(40) NOT NULL,
    etiqueta        VARCHAR(80) NOT NULL,
    ruta            VARCHAR(120) NOT NULL,
    icono           VARCHAR(40) NOT NULL,
    grupo           VARCHAR(40) NOT NULL,
    descripcion     VARCHAR(200),
    orden           INTEGER NOT NULL DEFAULT 0,
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_menu_item_codigo UNIQUE (codigo)
);

CREATE TABLE menu_rol (
    id_menu INTEGER NOT NULL REFERENCES menu_item (id_menu) ON DELETE CASCADE,
    id_rol  INTEGER NOT NULL REFERENCES rol (id_rol) ON DELETE CASCADE,
    PRIMARY KEY (id_menu, id_rol)
);

-- -----------------------------------------------------------------------------
-- Personal (SS-01, RI-01, RG-03)
-- id_jefe_inmediato pertenece al organigrama, no a la solicitud.
-- El flujo lo usa cuando un paso es de tipo JEFE_INMEDIATO.
-- -----------------------------------------------------------------------------
CREATE TABLE empleado (
    id_empleado         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_empleado     VARCHAR(20) NOT NULL,
    tipo_documento      tipo_documento NOT NULL DEFAULT 'DNI',
    numero_documento    VARCHAR(20) NOT NULL,
    nombres             VARCHAR(80) NOT NULL,
    apellido_paterno    VARCHAR(80) NOT NULL,
    apellido_materno    VARCHAR(80) NOT NULL,
    fecha_nacimiento    DATE,
    sexo                sexo_empleado,
    correo_institucional VARCHAR(120) NOT NULL,
    correo_personal     VARCHAR(120),
    telefono            VARCHAR(20),
    direccion           VARCHAR(200),
    fecha_ingreso       DATE NOT NULL,
    fecha_cese          DATE,
    id_area             INTEGER NOT NULL REFERENCES area (id_area),
    id_cargo            INTEGER NOT NULL REFERENCES cargo (id_cargo),
    id_horario          INTEGER NOT NULL REFERENCES horario_laboral (id_horario),
    tipo_contrato       tipo_contrato NOT NULL DEFAULT 'PLANILLA',
    estado              estado_empleado NOT NULL DEFAULT 'ACTIVO',
    id_jefe_inmediato   INTEGER REFERENCES empleado (id_empleado),
    fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_empleado_codigo UNIQUE (codigo_empleado),
    CONSTRAINT uq_empleado_documento UNIQUE (tipo_documento, numero_documento),
    CONSTRAINT uq_empleado_correo UNIQUE (correo_institucional),
    CONSTRAINT ck_empleado_cese CHECK (fecha_cese IS NULL OR fecha_cese >= fecha_ingreso),
    CONSTRAINT ck_empleado_nacimiento CHECK (fecha_nacimiento IS NULL OR fecha_nacimiento < fecha_ingreso),
    CONSTRAINT ck_empleado_dni CHECK (
        tipo_documento <> 'DNI' OR numero_documento ~ '^[0-9]{8}$'
    ),
    CONSTRAINT ck_empleado_no_autojefe CHECK (
        id_jefe_inmediato IS NULL OR id_jefe_inmediato <> id_empleado
    )
);

CREATE TABLE usuario (
    id_usuario          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empleado         INTEGER REFERENCES empleado (id_empleado),
    id_rol              INTEGER NOT NULL REFERENCES rol (id_rol),
    nombre_usuario      VARCHAR(60) NOT NULL,
    correo              VARCHAR(120) NOT NULL,
    password_hash       TEXT NOT NULL,
    activo              BOOLEAN NOT NULL DEFAULT TRUE,
    ultimo_acceso       TIMESTAMPTZ,
    fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_usuario_nombre UNIQUE (nombre_usuario),
    CONSTRAINT uq_usuario_correo UNIQUE (correo),
    CONSTRAINT uq_usuario_empleado UNIQUE (id_empleado)
);

-- -----------------------------------------------------------------------------
-- Asistencia (SS-04, RI-04, RG-11, RC-09)
-- -----------------------------------------------------------------------------
CREATE TABLE marcacion (
    id_marcacion        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empleado         INTEGER NOT NULL REFERENCES empleado (id_empleado),
    tipo                tipo_marcacion NOT NULL,
    fecha_hora          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha               DATE GENERATED ALWAYS AS ((fecha_hora AT TIME ZONE 'America/Lima')::date) STORED,
    origen              VARCHAR(20) NOT NULL DEFAULT 'WEB',
    observacion         VARCHAR(250),
    id_usuario_registro INTEGER REFERENCES usuario (id_usuario),
    fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_marcacion_origen CHECK (origen IN ('WEB', 'MANUAL', 'CORRECCION'))
);

-- -----------------------------------------------------------------------------
-- Configuración de aprobaciones (RG-06)
-- Un flujo por tipo de trámite. Vacaciones, salud, horas extras, etc.
-- pueden tener circuitos distintos (jefe -> RR. HH. -> gerencia).
-- -----------------------------------------------------------------------------
CREATE TABLE configuracion_aprobacion (
    id_configuracion    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo              VARCHAR(40) NOT NULL,
    nombre              VARCHAR(120) NOT NULL,
    tipo_origen         tipo_origen_flujo NOT NULL,
    id_tipo_permiso     INTEGER REFERENCES tipo_permiso (id_tipo_permiso),
    descripcion         VARCHAR(300),
    activo              BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_configuracion_codigo UNIQUE (codigo),
    CONSTRAINT ck_config_tipo_permiso CHECK (
        (tipo_origen = 'PERMISO')
        OR (tipo_origen = 'HORA_EXTRA' AND id_tipo_permiso IS NULL)
    )
);

CREATE TABLE configuracion_aprobacion_detalle (
    id_detalle          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_configuracion    INTEGER NOT NULL REFERENCES configuracion_aprobacion (id_configuracion) ON DELETE CASCADE,
    numero_paso         INTEGER NOT NULL,
    nombre_paso         VARCHAR(120) NOT NULL,
    tipo_aprobador      tipo_aprobador NOT NULL,
    id_rol              INTEGER REFERENCES rol (id_rol),
    id_usuario          INTEGER REFERENCES usuario (id_usuario),
    es_obligatorio      BOOLEAN NOT NULL DEFAULT TRUE,
    activo              BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_config_detalle_paso UNIQUE (id_configuracion, numero_paso),
    CONSTRAINT ck_config_detalle_paso CHECK (numero_paso >= 1),
    CONSTRAINT ck_config_detalle_aprobador CHECK (
        (tipo_aprobador = 'JEFE_INMEDIATO' AND id_rol IS NULL AND id_usuario IS NULL)
        OR (tipo_aprobador = 'ROL' AND id_rol IS NOT NULL AND id_usuario IS NULL)
        OR (tipo_aprobador = 'USUARIO' AND id_usuario IS NOT NULL AND id_rol IS NULL)
    )
);

CREATE UNIQUE INDEX uq_config_activa_especifica
    ON configuracion_aprobacion (tipo_origen, id_tipo_permiso)
    WHERE activo AND id_tipo_permiso IS NOT NULL;

CREATE UNIQUE INDEX uq_config_activa_generica
    ON configuracion_aprobacion (tipo_origen)
    WHERE activo AND id_tipo_permiso IS NULL;

-- -----------------------------------------------------------------------------
-- Permisos (SS-02, RI-02, RG-04)
-- Solo datos del pedido. El circuito vive en la configuración y en los pasos.
-- -----------------------------------------------------------------------------
CREATE TABLE solicitud_permiso (
    id_solicitud_permiso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empleado         INTEGER NOT NULL REFERENCES empleado (id_empleado),
    id_tipo_permiso     INTEGER NOT NULL REFERENCES tipo_permiso (id_tipo_permiso),
    id_configuracion    INTEGER REFERENCES configuracion_aprobacion (id_configuracion),
    fecha_inicio        DATE NOT NULL,
    fecha_fin           DATE NOT NULL,
    hora_inicio         TIME,
    hora_fin            TIME,
    motivo              VARCHAR(400) NOT NULL,
    estado              estado_solicitud NOT NULL DEFAULT 'PENDIENTE',
    fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_permiso_rango_fechas CHECK (fecha_fin >= fecha_inicio),
    CONSTRAINT ck_permiso_horas CHECK (
        (hora_inicio IS NULL AND hora_fin IS NULL)
        OR (hora_inicio IS NOT NULL AND hora_fin IS NOT NULL AND hora_fin > hora_inicio)
    ),
    CONSTRAINT ck_permiso_motivo CHECK (length(btrim(motivo)) >= 5)
);

-- -----------------------------------------------------------------------------
-- Horas extras (SS-03, RI-03, RG-05)
-- -----------------------------------------------------------------------------
CREATE TABLE solicitud_hora_extra (
    id_solicitud_hora_extra INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empleado         INTEGER NOT NULL REFERENCES empleado (id_empleado),
    id_configuracion    INTEGER REFERENCES configuracion_aprobacion (id_configuracion),
    fecha               DATE NOT NULL,
    hora_inicio         TIME NOT NULL,
    hora_fin            TIME NOT NULL,
    cantidad_horas      NUMERIC(5,2) NOT NULL,
    motivo              VARCHAR(400) NOT NULL,
    estado              estado_solicitud NOT NULL DEFAULT 'PENDIENTE',
    fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_hora_extra_rango CHECK (hora_fin > hora_inicio),
    CONSTRAINT ck_hora_extra_cantidad CHECK (cantidad_horas > 0 AND cantidad_horas <= 8),
    CONSTRAINT ck_hora_extra_motivo CHECK (length(btrim(motivo)) >= 5)
);

-- -----------------------------------------------------------------------------
-- Pasos reales de cada solicitud (instancia del detalle configurado)
-- -----------------------------------------------------------------------------
CREATE TABLE solicitud_paso_aprobacion (
    id_paso_solicitud       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_solicitud_permiso    INTEGER REFERENCES solicitud_permiso (id_solicitud_permiso) ON DELETE CASCADE,
    id_solicitud_hora_extra INTEGER REFERENCES solicitud_hora_extra (id_solicitud_hora_extra) ON DELETE CASCADE,
    id_configuracion        INTEGER NOT NULL REFERENCES configuracion_aprobacion (id_configuracion),
    id_detalle              INTEGER NOT NULL REFERENCES configuracion_aprobacion_detalle (id_detalle),
    numero_paso             INTEGER NOT NULL,
    nombre_paso             VARCHAR(120) NOT NULL,
    tipo_aprobador          tipo_aprobador NOT NULL,
    id_rol                  INTEGER REFERENCES rol (id_rol),
    id_usuario_asignado     INTEGER REFERENCES usuario (id_usuario),
    estado                  estado_paso_aprobacion NOT NULL DEFAULT 'PENDIENTE',
    id_usuario_decision     INTEGER REFERENCES usuario (id_usuario),
    fecha_inicio            TIMESTAMPTZ,
    fecha_decision          TIMESTAMPTZ,
    comentario              VARCHAR(400),
    fecha_creacion          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_paso_una_solicitud CHECK (
        (id_solicitud_permiso IS NOT NULL AND id_solicitud_hora_extra IS NULL)
        OR (id_solicitud_permiso IS NULL AND id_solicitud_hora_extra IS NOT NULL)
    ),
    CONSTRAINT ck_paso_numero CHECK (numero_paso >= 1),
    CONSTRAINT ck_paso_decision CHECK (
        estado NOT IN ('APROBADO', 'RECHAZADO')
        OR (id_usuario_decision IS NOT NULL AND fecha_decision IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uq_paso_permiso_numero
    ON solicitud_paso_aprobacion (id_solicitud_permiso, numero_paso)
    WHERE id_solicitud_permiso IS NOT NULL;

CREATE UNIQUE INDEX uq_paso_hora_extra_numero
    ON solicitud_paso_aprobacion (id_solicitud_hora_extra, numero_paso)
    WHERE id_solicitud_hora_extra IS NOT NULL;

CREATE UNIQUE INDEX uq_paso_permiso_en_curso
    ON solicitud_paso_aprobacion (id_solicitud_permiso)
    WHERE id_solicitud_permiso IS NOT NULL AND estado = 'EN_CURSO';

CREATE UNIQUE INDEX uq_paso_hora_extra_en_curso
    ON solicitud_paso_aprobacion (id_solicitud_hora_extra)
    WHERE id_solicitud_hora_extra IS NOT NULL AND estado = 'EN_CURSO';

-- -----------------------------------------------------------------------------
-- Trazabilidad de solicitudes (SS-07, RI-06, RG-07, RRN-04)
-- -----------------------------------------------------------------------------
CREATE TABLE historial_solicitud (
    id_historial            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_solicitud_permiso    INTEGER REFERENCES solicitud_permiso (id_solicitud_permiso) ON DELETE CASCADE,
    id_solicitud_hora_extra INTEGER REFERENCES solicitud_hora_extra (id_solicitud_hora_extra) ON DELETE CASCADE,
    id_paso_solicitud       INTEGER REFERENCES solicitud_paso_aprobacion (id_paso_solicitud) ON DELETE SET NULL,
    id_usuario              INTEGER NOT NULL REFERENCES usuario (id_usuario),
    accion                  accion_solicitud NOT NULL,
    estado_anterior         estado_solicitud,
    estado_nuevo            estado_solicitud NOT NULL,
    comentario              VARCHAR(400),
    fecha_hora              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_historial_una_solicitud CHECK (
        (id_solicitud_permiso IS NOT NULL AND id_solicitud_hora_extra IS NULL)
        OR (id_solicitud_permiso IS NULL AND id_solicitud_hora_extra IS NOT NULL)
    )
);

-- -----------------------------------------------------------------------------
-- Auditoría general (SS-07, RI-06, RG-14, RNF-S03)
-- -----------------------------------------------------------------------------
CREATE TABLE auditoria (
    id_auditoria    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario      INTEGER REFERENCES usuario (id_usuario),
    accion          VARCHAR(80) NOT NULL,
    entidad         VARCHAR(60) NOT NULL,
    id_entidad      INTEGER,
    detalle         JSONB,
    direccion_ip    VARCHAR(45),
    fecha_hora      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- Carga masiva Excel (RI-08, INT-01, PNI-01)
-- -----------------------------------------------------------------------------
CREATE TABLE carga_masiva (
    id_carga            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario          INTEGER NOT NULL REFERENCES usuario (id_usuario),
    nombre_archivo      VARCHAR(255) NOT NULL,
    total_filas         INTEGER NOT NULL DEFAULT 0,
    filas_exitosas      INTEGER NOT NULL DEFAULT 0,
    filas_fallidas      INTEGER NOT NULL DEFAULT 0,
    estado              estado_carga NOT NULL DEFAULT 'PROCESANDO',
    mensaje             VARCHAR(400),
    fecha_inicio        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_fin           TIMESTAMPTZ,
    CONSTRAINT ck_carga_totales CHECK (
        total_filas >= 0
        AND filas_exitosas >= 0
        AND filas_fallidas >= 0
        AND filas_exitosas + filas_fallidas <= total_filas
    )
);

CREATE TABLE carga_masiva_detalle (
    id_detalle      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_carga        INTEGER NOT NULL REFERENCES carga_masiva (id_carga) ON DELETE CASCADE,
    numero_fila     INTEGER NOT NULL,
    resultado       resultado_fila_carga NOT NULL,
    id_empleado     INTEGER REFERENCES empleado (id_empleado),
    mensaje         VARCHAR(400),
    datos           JSONB,
    CONSTRAINT uq_carga_fila UNIQUE (id_carga, numero_fila)
);

-- -----------------------------------------------------------------------------
-- Registro de reportes exportados (SS-06, RI-07)
-- -----------------------------------------------------------------------------
CREATE TABLE reporte_generado (
    id_reporte      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario      INTEGER NOT NULL REFERENCES usuario (id_usuario),
    tipo            tipo_reporte NOT NULL,
    formato         formato_reporte NOT NULL,
    filtros         JSONB,
    fecha_generacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE refresh_token (
    id_refresh_token    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario          INTEGER NOT NULL REFERENCES usuario (id_usuario) ON DELETE CASCADE,
    token               VARCHAR(200) NOT NULL,
    fecha_expiracion    TIMESTAMPTZ NOT NULL,
    revocado            BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_refresh_token UNIQUE (token)
);

CREATE INDEX ix_refresh_token_usuario ON refresh_token (id_usuario, revocado);

-- -----------------------------------------------------------------------------
-- Índices para consultas y reportes
-- -----------------------------------------------------------------------------
CREATE INDEX ix_empleado_area ON empleado (id_area);
CREATE INDEX ix_empleado_estado ON empleado (estado);
CREATE INDEX ix_empleado_jefe ON empleado (id_jefe_inmediato);
CREATE INDEX ix_usuario_rol ON usuario (id_rol);
CREATE INDEX ix_marcacion_empleado_fecha ON marcacion (id_empleado, fecha);
CREATE INDEX ix_marcacion_fecha ON marcacion (fecha);
CREATE INDEX ix_permiso_empleado ON solicitud_permiso (id_empleado);
CREATE INDEX ix_permiso_estado ON solicitud_permiso (estado);
CREATE INDEX ix_permiso_fechas ON solicitud_permiso (fecha_inicio, fecha_fin);
CREATE INDEX ix_permiso_config ON solicitud_permiso (id_configuracion);
CREATE INDEX ix_hora_extra_empleado ON solicitud_hora_extra (id_empleado);
CREATE INDEX ix_hora_extra_estado ON solicitud_hora_extra (estado);
CREATE INDEX ix_hora_extra_fecha ON solicitud_hora_extra (fecha);
CREATE INDEX ix_hora_extra_config ON solicitud_hora_extra (id_configuracion);
CREATE INDEX ix_config_detalle_config ON configuracion_aprobacion_detalle (id_configuracion, numero_paso);
CREATE INDEX ix_paso_permiso ON solicitud_paso_aprobacion (id_solicitud_permiso, estado);
CREATE INDEX ix_paso_hora_extra ON solicitud_paso_aprobacion (id_solicitud_hora_extra, estado);
CREATE INDEX ix_paso_asignado ON solicitud_paso_aprobacion (id_usuario_asignado, estado);
CREATE INDEX ix_paso_rol ON solicitud_paso_aprobacion (id_rol, estado);
CREATE INDEX ix_historial_permiso ON historial_solicitud (id_solicitud_permiso);
CREATE INDEX ix_historial_hora_extra ON historial_solicitud (id_solicitud_hora_extra);
CREATE INDEX ix_auditoria_entidad ON auditoria (entidad, id_entidad);
CREATE INDEX ix_auditoria_usuario_fecha ON auditoria (id_usuario, fecha_hora DESC);
CREATE INDEX ix_auditoria_fecha ON auditoria (fecha_hora DESC);

CREATE UNIQUE INDEX uq_hora_extra_pendiente_dia
    ON solicitud_hora_extra (id_empleado, fecha)
    WHERE estado = 'PENDIENTE';

-- -----------------------------------------------------------------------------
-- Funciones y triggers
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_set_fecha_actualizacion()
RETURNS TRIGGER AS $$
BEGIN
    NEW.fecha_actualizacion := NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_area_actualizacion
    BEFORE UPDATE ON area
    FOR EACH ROW EXECUTE FUNCTION fn_set_fecha_actualizacion();

CREATE TRIGGER trg_cargo_actualizacion
    BEFORE UPDATE ON cargo
    FOR EACH ROW EXECUTE FUNCTION fn_set_fecha_actualizacion();

CREATE TRIGGER trg_horario_actualizacion
    BEFORE UPDATE ON horario_laboral
    FOR EACH ROW EXECUTE FUNCTION fn_set_fecha_actualizacion();

CREATE TRIGGER trg_empleado_actualizacion
    BEFORE UPDATE ON empleado
    FOR EACH ROW EXECUTE FUNCTION fn_set_fecha_actualizacion();

CREATE TRIGGER trg_usuario_actualizacion
    BEFORE UPDATE ON usuario
    FOR EACH ROW EXECUTE FUNCTION fn_set_fecha_actualizacion();

CREATE TRIGGER trg_config_actualizacion
    BEFORE UPDATE ON configuracion_aprobacion
    FOR EACH ROW EXECUTE FUNCTION fn_set_fecha_actualizacion();

CREATE TRIGGER trg_permiso_actualizacion
    BEFORE UPDATE ON solicitud_permiso
    FOR EACH ROW EXECUTE FUNCTION fn_set_fecha_actualizacion();

CREATE TRIGGER trg_hora_extra_actualizacion
    BEFORE UPDATE ON solicitud_hora_extra
    FOR EACH ROW EXECUTE FUNCTION fn_set_fecha_actualizacion();

CREATE OR REPLACE FUNCTION fn_validar_empleado_activo()
RETURNS TRIGGER AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM empleado
        WHERE id_empleado = NEW.id_empleado
          AND estado = 'ACTIVO'
    ) THEN
        RAISE EXCEPTION 'El trabajador % no está activo.', NEW.id_empleado;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_marcacion_empleado_activo
    BEFORE INSERT ON marcacion
    FOR EACH ROW EXECUTE FUNCTION fn_validar_empleado_activo();

CREATE TRIGGER trg_permiso_empleado_activo
    BEFORE INSERT ON solicitud_permiso
    FOR EACH ROW EXECUTE FUNCTION fn_validar_empleado_activo();

CREATE TRIGGER trg_hora_extra_empleado_activo
    BEFORE INSERT ON solicitud_hora_extra
    FOR EACH ROW EXECUTE FUNCTION fn_validar_empleado_activo();

CREATE OR REPLACE FUNCTION fn_resolver_configuracion(
    p_tipo_origen tipo_origen_flujo,
    p_id_tipo_permiso INTEGER DEFAULT NULL
)
RETURNS INTEGER AS $$
DECLARE
    v_id INTEGER;
BEGIN
    IF p_tipo_origen = 'PERMISO' AND p_id_tipo_permiso IS NOT NULL THEN
        SELECT id_configuracion INTO v_id
        FROM configuracion_aprobacion
        WHERE activo
          AND tipo_origen = 'PERMISO'
          AND id_tipo_permiso = p_id_tipo_permiso
        LIMIT 1;
    END IF;

    IF v_id IS NULL THEN
        SELECT id_configuracion INTO v_id
        FROM configuracion_aprobacion
        WHERE activo
          AND tipo_origen = p_tipo_origen
          AND id_tipo_permiso IS NULL
        LIMIT 1;
    END IF;

    IF v_id IS NULL THEN
        RAISE EXCEPTION 'No existe una configuración de aprobación activa para %.', p_tipo_origen;
    END IF;

    RETURN v_id;
END;
$$ LANGUAGE plpgsql STABLE;

CREATE OR REPLACE FUNCTION fn_resolver_aprobador(
    p_tipo_aprobador tipo_aprobador,
    p_id_rol INTEGER,
    p_id_usuario INTEGER,
    p_id_empleado INTEGER
)
RETURNS INTEGER AS $$
DECLARE
    v_id_usuario INTEGER;
BEGIN
    IF p_tipo_aprobador = 'USUARIO' THEN
        SELECT id_usuario INTO v_id_usuario
        FROM usuario
        WHERE id_usuario = p_id_usuario
          AND activo;
    ELSIF p_tipo_aprobador = 'JEFE_INMEDIATO' THEN
        SELECT u.id_usuario INTO v_id_usuario
        FROM empleado e
        JOIN usuario u ON u.id_empleado = e.id_jefe_inmediato
        WHERE e.id_empleado = p_id_empleado
          AND u.activo;
    ELSIF p_tipo_aprobador = 'ROL' THEN
        v_id_usuario := NULL;
    END IF;

    RETURN v_id_usuario;
END;
$$ LANGUAGE plpgsql STABLE;

CREATE OR REPLACE FUNCTION fn_asignar_configuracion_permiso()
RETURNS TRIGGER AS $$
BEGIN
    NEW.id_configuracion := fn_resolver_configuracion('PERMISO', NEW.id_tipo_permiso);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_asignar_configuracion_hora_extra()
RETURNS TRIGGER AS $$
BEGIN
    NEW.id_configuracion := fn_resolver_configuracion('HORA_EXTRA');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_permiso_configuracion
    BEFORE INSERT ON solicitud_permiso
    FOR EACH ROW EXECUTE FUNCTION fn_asignar_configuracion_permiso();

CREATE TRIGGER trg_hora_extra_configuracion
    BEFORE INSERT ON solicitud_hora_extra
    FOR EACH ROW EXECUTE FUNCTION fn_asignar_configuracion_hora_extra();

CREATE OR REPLACE FUNCTION fn_instanciar_pasos_aprobacion()
RETURNS TRIGGER AS $$
DECLARE
    v_detalle RECORD;
    v_id_usuario INTEGER;
    v_estado estado_paso_aprobacion;
    v_id_empleado INTEGER;
    v_id_config INTEGER;
    v_id_permiso INTEGER;
    v_id_hextra INTEGER;
    v_motivo VARCHAR(400);
    v_hay_en_curso BOOLEAN := FALSE;
    v_id_usuario_solicitante INTEGER;
BEGIN
    v_id_empleado := NEW.id_empleado;
    v_id_config := NEW.id_configuracion;
    v_motivo := NEW.motivo;

    IF TG_TABLE_NAME = 'solicitud_permiso' THEN
        v_id_permiso := NEW.id_solicitud_permiso;
    ELSE
        v_id_hextra := NEW.id_solicitud_hora_extra;
    END IF;

    SELECT id_usuario INTO v_id_usuario_solicitante
    FROM usuario
    WHERE id_empleado = v_id_empleado
    LIMIT 1;

    IF NOT EXISTS (
        SELECT 1
        FROM configuracion_aprobacion_detalle
        WHERE id_configuracion = v_id_config
          AND activo
    ) THEN
        RAISE EXCEPTION 'La configuración % no tiene pasos de aprobación activos.', v_id_config;
    END IF;

    FOR v_detalle IN
        SELECT *
        FROM configuracion_aprobacion_detalle
        WHERE id_configuracion = v_id_config
          AND activo
        ORDER BY numero_paso
    LOOP
        v_id_usuario := fn_resolver_aprobador(
            v_detalle.tipo_aprobador,
            v_detalle.id_rol,
            v_detalle.id_usuario,
            v_id_empleado
        );

        IF v_detalle.tipo_aprobador <> 'ROL' AND v_id_usuario IS NULL THEN
            IF v_detalle.es_obligatorio THEN
                RAISE EXCEPTION 'No se pudo resolver el aprobador del paso "%" (%).',
                    v_detalle.nombre_paso, v_detalle.tipo_aprobador;
            END IF;
            v_estado := 'OMITIDO';
        ELSIF NOT v_hay_en_curso THEN
            v_estado := 'EN_CURSO';
            v_hay_en_curso := TRUE;
        ELSE
            v_estado := 'PENDIENTE';
        END IF;

        INSERT INTO solicitud_paso_aprobacion (
            id_solicitud_permiso,
            id_solicitud_hora_extra,
            id_configuracion,
            id_detalle,
            numero_paso,
            nombre_paso,
            tipo_aprobador,
            id_rol,
            id_usuario_asignado,
            estado,
            fecha_inicio
        ) VALUES (
            v_id_permiso,
            v_id_hextra,
            v_id_config,
            v_detalle.id_detalle,
            v_detalle.numero_paso,
            v_detalle.nombre_paso,
            v_detalle.tipo_aprobador,
            v_detalle.id_rol,
            v_id_usuario,
            v_estado,
            CASE WHEN v_estado = 'EN_CURSO' THEN NOW() END
        );
    END LOOP;

    IF v_id_usuario_solicitante IS NOT NULL THEN
        INSERT INTO historial_solicitud (
            id_solicitud_permiso,
            id_solicitud_hora_extra,
            id_usuario,
            accion,
            estado_anterior,
            estado_nuevo,
            comentario
        ) VALUES (
            v_id_permiso,
            v_id_hextra,
            v_id_usuario_solicitante,
            'REGISTRAR',
            NULL,
            'PENDIENTE'::estado_solicitud,
            v_motivo
        );
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_permiso_instanciar_flujo
    AFTER INSERT ON solicitud_permiso
    FOR EACH ROW EXECUTE FUNCTION fn_instanciar_pasos_aprobacion();

CREATE TRIGGER trg_hora_extra_instanciar_flujo
    AFTER INSERT ON solicitud_hora_extra
    FOR EACH ROW EXECUTE FUNCTION fn_instanciar_pasos_aprobacion();

CREATE OR REPLACE FUNCTION fn_usuario_puede_decidir_paso(
    p_id_paso INTEGER,
    p_id_usuario INTEGER
)
RETURNS BOOLEAN AS $$
DECLARE
    v_paso solicitud_paso_aprobacion%ROWTYPE;
    v_id_rol INTEGER;
BEGIN
    SELECT * INTO v_paso
    FROM solicitud_paso_aprobacion
    WHERE id_paso_solicitud = p_id_paso;

    IF NOT FOUND OR v_paso.estado <> 'EN_CURSO' THEN
        RETURN FALSE;
    END IF;

    SELECT id_rol INTO v_id_rol
    FROM usuario
    WHERE id_usuario = p_id_usuario
      AND activo;

    IF v_id_rol IS NULL THEN
        RETURN FALSE;
    END IF;

    IF v_paso.tipo_aprobador IN ('JEFE_INMEDIATO', 'USUARIO') THEN
        RETURN v_paso.id_usuario_asignado = p_id_usuario;
    END IF;

    RETURN v_paso.id_rol = v_id_rol;
END;
$$ LANGUAGE plpgsql STABLE;

CREATE OR REPLACE FUNCTION fn_validar_decision_paso()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.estado <> 'EN_CURSO' AND NEW.estado IN ('APROBADO', 'RECHAZADO') THEN
        RAISE EXCEPTION 'Solo se puede decidir el paso que está en curso.';
    END IF;

    IF NEW.estado IN ('APROBADO', 'RECHAZADO') THEN
        IF NEW.id_usuario_decision IS NULL THEN
            RAISE EXCEPTION 'Debe indicarse el usuario que toma la decisión.';
        END IF;
        IF NOT fn_usuario_puede_decidir_paso(NEW.id_paso_solicitud, NEW.id_usuario_decision) THEN
            RAISE EXCEPTION 'El usuario % no está autorizado para el paso %.',
                NEW.id_usuario_decision, NEW.nombre_paso;
        END IF;
        NEW.fecha_decision := COALESCE(NEW.fecha_decision, NOW());
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_validar_decision_paso
    BEFORE UPDATE OF estado ON solicitud_paso_aprobacion
    FOR EACH ROW
    WHEN (OLD.estado IS DISTINCT FROM NEW.estado)
    EXECUTE FUNCTION fn_validar_decision_paso();

CREATE OR REPLACE FUNCTION fn_avanzar_flujo_aprobacion()
RETURNS TRIGGER AS $$
DECLARE
    v_siguiente INTEGER;
    v_accion accion_solicitud;
    v_estado_final estado_solicitud;
BEGIN
    v_accion := CASE NEW.estado
        WHEN 'APROBADO' THEN 'APROBAR'::accion_solicitud
        ELSE 'RECHAZAR'::accion_solicitud
    END;

    INSERT INTO historial_solicitud (
        id_solicitud_permiso,
        id_solicitud_hora_extra,
        id_paso_solicitud,
        id_usuario,
        accion,
        estado_anterior,
        estado_nuevo,
        comentario
    ) VALUES (
        NEW.id_solicitud_permiso,
        NEW.id_solicitud_hora_extra,
        NEW.id_paso_solicitud,
        NEW.id_usuario_decision,
        v_accion,
        'PENDIENTE'::estado_solicitud,
        CASE
            WHEN NEW.estado = 'APROBADO' THEN 'PENDIENTE'::estado_solicitud
            ELSE 'RECHAZADO'::estado_solicitud
        END,
        NEW.comentario
    );

    IF NEW.estado = 'RECHAZADO' THEN
        UPDATE solicitud_paso_aprobacion
        SET estado = 'OMITIDO'
        WHERE estado IN ('PENDIENTE')
          AND id_paso_solicitud <> NEW.id_paso_solicitud
          AND (
              (NEW.id_solicitud_permiso IS NOT NULL AND id_solicitud_permiso = NEW.id_solicitud_permiso)
              OR (NEW.id_solicitud_hora_extra IS NOT NULL AND id_solicitud_hora_extra = NEW.id_solicitud_hora_extra)
          );

        v_estado_final := 'RECHAZADO';
    ELSE
        SELECT id_paso_solicitud INTO v_siguiente
        FROM solicitud_paso_aprobacion
        WHERE estado = 'PENDIENTE'
          AND (
              (NEW.id_solicitud_permiso IS NOT NULL AND id_solicitud_permiso = NEW.id_solicitud_permiso)
              OR (NEW.id_solicitud_hora_extra IS NOT NULL AND id_solicitud_hora_extra = NEW.id_solicitud_hora_extra)
          )
        ORDER BY numero_paso
        LIMIT 1;

        IF v_siguiente IS NOT NULL THEN
            UPDATE solicitud_paso_aprobacion
            SET estado = 'EN_CURSO',
                fecha_inicio = NOW()
            WHERE id_paso_solicitud = v_siguiente;
            RETURN NEW;
        END IF;

        v_estado_final := 'APROBADO';
    END IF;

    IF NEW.id_solicitud_permiso IS NOT NULL THEN
        UPDATE solicitud_permiso
        SET estado = v_estado_final
        WHERE id_solicitud_permiso = NEW.id_solicitud_permiso;
    ELSE
        UPDATE solicitud_hora_extra
        SET estado = v_estado_final
        WHERE id_solicitud_hora_extra = NEW.id_solicitud_hora_extra;
    END IF;

    INSERT INTO historial_solicitud (
        id_solicitud_permiso,
        id_solicitud_hora_extra,
        id_paso_solicitud,
        id_usuario,
        accion,
        estado_anterior,
        estado_nuevo,
        comentario
    ) VALUES (
        NEW.id_solicitud_permiso,
        NEW.id_solicitud_hora_extra,
        NEW.id_paso_solicitud,
        NEW.id_usuario_decision,
        v_accion,
        'PENDIENTE'::estado_solicitud,
        v_estado_final,
        NEW.comentario
    );

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_avanzar_flujo_aprobacion
    AFTER UPDATE OF estado ON solicitud_paso_aprobacion
    FOR EACH ROW
    WHEN (OLD.estado = 'EN_CURSO' AND NEW.estado IN ('APROBADO', 'RECHAZADO'))
    EXECUTE FUNCTION fn_avanzar_flujo_aprobacion();

CREATE OR REPLACE FUNCTION fn_cancelar_pasos_solicitud()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.estado = 'CANCELADO' AND OLD.estado IS DISTINCT FROM 'CANCELADO' THEN
        IF TG_TABLE_NAME = 'solicitud_permiso' THEN
            UPDATE solicitud_paso_aprobacion
            SET estado = 'CANCELADO'
            WHERE estado IN ('PENDIENTE', 'EN_CURSO')
              AND id_solicitud_permiso = NEW.id_solicitud_permiso;
        ELSE
            UPDATE solicitud_paso_aprobacion
            SET estado = 'CANCELADO'
            WHERE estado IN ('PENDIENTE', 'EN_CURSO')
              AND id_solicitud_hora_extra = NEW.id_solicitud_hora_extra;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_cancelar_pasos_permiso
    AFTER UPDATE OF estado ON solicitud_permiso
    FOR EACH ROW EXECUTE FUNCTION fn_cancelar_pasos_solicitud();

CREATE TRIGGER trg_cancelar_pasos_hora_extra
    AFTER UPDATE OF estado ON solicitud_hora_extra
    FOR EACH ROW EXECUTE FUNCTION fn_cancelar_pasos_solicitud();

CREATE OR REPLACE FUNCTION fn_validar_hora_extra()
RETURNS TRIGGER AS $$
DECLARE
    v_max_diarias NUMERIC;
    v_max_semanales NUMERIC;
    v_acumulado_dia NUMERIC;
    v_acumulado_semana NUMERIC;
BEGIN
    SELECT valor::NUMERIC INTO v_max_diarias
    FROM parametro_sistema WHERE clave = 'max_horas_extras_diarias';

    SELECT valor::NUMERIC INTO v_max_semanales
    FROM parametro_sistema WHERE clave = 'max_horas_extras_semanales';

    SELECT COALESCE(SUM(cantidad_horas), 0) INTO v_acumulado_dia
    FROM solicitud_hora_extra
    WHERE id_empleado = NEW.id_empleado
      AND fecha = NEW.fecha
      AND estado IN ('PENDIENTE', 'APROBADO')
      AND (TG_OP = 'INSERT' OR id_solicitud_hora_extra <> NEW.id_solicitud_hora_extra);

    IF v_acumulado_dia + NEW.cantidad_horas > COALESCE(v_max_diarias, 4) THEN
        RAISE EXCEPTION 'La cantidad de horas extras del día supera el máximo permitido (%).',
            COALESCE(v_max_diarias, 4);
    END IF;

    SELECT COALESCE(SUM(cantidad_horas), 0) INTO v_acumulado_semana
    FROM solicitud_hora_extra
    WHERE id_empleado = NEW.id_empleado
      AND fecha >= date_trunc('week', NEW.fecha)::date
      AND fecha < date_trunc('week', NEW.fecha)::date + 7
      AND estado IN ('PENDIENTE', 'APROBADO')
      AND (TG_OP = 'INSERT' OR id_solicitud_hora_extra <> NEW.id_solicitud_hora_extra);

    IF v_acumulado_semana + NEW.cantidad_horas > COALESCE(v_max_semanales, 12) THEN
        RAISE EXCEPTION 'La cantidad de horas extras de la semana supera el máximo permitido (%).',
            COALESCE(v_max_semanales, 12);
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_validar_hora_extra
    BEFORE INSERT OR UPDATE OF cantidad_horas, fecha, estado ON solicitud_hora_extra
    FOR EACH ROW
    WHEN (NEW.estado IN ('PENDIENTE', 'APROBADO'))
    EXECUTE FUNCTION fn_validar_hora_extra();

-- -----------------------------------------------------------------------------
-- Vistas de reporte (SS-06, CU-16 a CU-19)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW v_empleado AS
SELECT
    e.id_empleado,
    e.codigo_empleado,
    e.tipo_documento,
    e.numero_documento,
    e.nombres,
    e.apellido_paterno,
    e.apellido_materno,
    trim(both FROM concat_ws(' ', e.nombres, e.apellido_paterno, e.apellido_materno)) AS nombre_completo,
    e.correo_institucional,
    e.telefono,
    e.fecha_ingreso,
    e.fecha_cese,
    e.tipo_contrato,
    e.estado,
    a.nombre AS area,
    c.nombre AS cargo,
    h.nombre AS horario,
    h.hora_ingreso,
    h.hora_salida,
    trim(both FROM concat_ws(' ', j.nombres, j.apellido_paterno, j.apellido_materno)) AS jefe_inmediato
FROM empleado e
JOIN area a ON a.id_area = e.id_area
JOIN cargo c ON c.id_cargo = e.id_cargo
JOIN horario_laboral h ON h.id_horario = e.id_horario
LEFT JOIN empleado j ON j.id_empleado = e.id_jefe_inmediato;

CREATE OR REPLACE VIEW v_configuracion_aprobacion AS
SELECT
    c.id_configuracion,
    c.codigo,
    c.nombre,
    c.tipo_origen,
    tp.codigo AS codigo_tipo_permiso,
    tp.nombre AS tipo_permiso,
    d.id_detalle,
    d.numero_paso,
    d.nombre_paso,
    d.tipo_aprobador,
    r.codigo AS codigo_rol,
    r.nombre AS rol,
    u.nombre_usuario,
    d.es_obligatorio,
    c.activo
FROM configuracion_aprobacion c
JOIN configuracion_aprobacion_detalle d ON d.id_configuracion = c.id_configuracion
LEFT JOIN tipo_permiso tp ON tp.id_tipo_permiso = c.id_tipo_permiso
LEFT JOIN rol r ON r.id_rol = d.id_rol
LEFT JOIN usuario u ON u.id_usuario = d.id_usuario
ORDER BY c.codigo, d.numero_paso;

CREATE OR REPLACE VIEW v_reporte_usuarios AS
SELECT
    u.id_usuario,
    u.nombre_usuario,
    u.correo,
    u.activo,
    u.ultimo_acceso,
    u.fecha_creacion,
    r.codigo AS codigo_rol,
    r.nombre AS rol,
    e.codigo_empleado,
    ve.nombre_completo,
    ve.area,
    ve.cargo
FROM usuario u
JOIN rol r ON r.id_rol = u.id_rol
LEFT JOIN empleado e ON e.id_empleado = u.id_empleado
LEFT JOIN v_empleado ve ON ve.id_empleado = e.id_empleado;

CREATE OR REPLACE VIEW v_reporte_permisos AS
SELECT
    sp.id_solicitud_permiso,
    ve.codigo_empleado,
    ve.nombre_completo,
    ve.area,
    tp.nombre AS tipo_permiso,
    cfg.nombre AS flujo_aprobacion,
    sp.fecha_inicio,
    sp.fecha_fin,
    (sp.fecha_fin - sp.fecha_inicio) + 1 AS dias,
    sp.motivo,
    sp.estado,
    paso.nombre_paso AS paso_actual,
    paso.tipo_aprobador AS tipo_aprobador_actual,
    COALESCE(ua.nombre_usuario, r.nombre) AS responsable_actual,
    ult.nombre_usuario AS ultimo_decisor,
    ult.fecha_decision,
    ult.comentario AS comentario_decision,
    sp.fecha_creacion
FROM solicitud_permiso sp
JOIN v_empleado ve ON ve.id_empleado = sp.id_empleado
JOIN tipo_permiso tp ON tp.id_tipo_permiso = sp.id_tipo_permiso
LEFT JOIN configuracion_aprobacion cfg ON cfg.id_configuracion = sp.id_configuracion
LEFT JOIN solicitud_paso_aprobacion paso
    ON paso.id_solicitud_permiso = sp.id_solicitud_permiso
   AND paso.estado = 'EN_CURSO'
LEFT JOIN usuario ua ON ua.id_usuario = paso.id_usuario_asignado
LEFT JOIN rol r ON r.id_rol = paso.id_rol
LEFT JOIN LATERAL (
    SELECT u.nombre_usuario, p.fecha_decision, p.comentario
    FROM solicitud_paso_aprobacion p
    JOIN usuario u ON u.id_usuario = p.id_usuario_decision
    WHERE p.id_solicitud_permiso = sp.id_solicitud_permiso
      AND p.estado IN ('APROBADO', 'RECHAZADO')
    ORDER BY p.numero_paso DESC
    LIMIT 1
) ult ON TRUE;

CREATE OR REPLACE VIEW v_reporte_horas_extras AS
SELECT
    he.id_solicitud_hora_extra,
    ve.codigo_empleado,
    ve.nombre_completo,
    ve.area,
    cfg.nombre AS flujo_aprobacion,
    he.fecha,
    he.hora_inicio,
    he.hora_fin,
    he.cantidad_horas,
    he.motivo,
    he.estado,
    paso.nombre_paso AS paso_actual,
    COALESCE(ua.nombre_usuario, r.nombre) AS responsable_actual,
    ult.nombre_usuario AS ultimo_decisor,
    ult.fecha_decision,
    ult.comentario AS comentario_decision,
    he.fecha_creacion
FROM solicitud_hora_extra he
JOIN v_empleado ve ON ve.id_empleado = he.id_empleado
LEFT JOIN configuracion_aprobacion cfg ON cfg.id_configuracion = he.id_configuracion
LEFT JOIN solicitud_paso_aprobacion paso
    ON paso.id_solicitud_hora_extra = he.id_solicitud_hora_extra
   AND paso.estado = 'EN_CURSO'
LEFT JOIN usuario ua ON ua.id_usuario = paso.id_usuario_asignado
LEFT JOIN rol r ON r.id_rol = paso.id_rol
LEFT JOIN LATERAL (
    SELECT u.nombre_usuario, p.fecha_decision, p.comentario
    FROM solicitud_paso_aprobacion p
    JOIN usuario u ON u.id_usuario = p.id_usuario_decision
    WHERE p.id_solicitud_hora_extra = he.id_solicitud_hora_extra
      AND p.estado IN ('APROBADO', 'RECHAZADO')
    ORDER BY p.numero_paso DESC
    LIMIT 1
) ult ON TRUE;

CREATE OR REPLACE VIEW v_pasos_solicitud AS
SELECT
    p.id_paso_solicitud,
    CASE
        WHEN p.id_solicitud_permiso IS NOT NULL THEN 'PERMISO'
        ELSE 'HORA_EXTRA'
    END AS tipo_solicitud,
    COALESCE(p.id_solicitud_permiso, p.id_solicitud_hora_extra) AS id_solicitud,
    p.numero_paso,
    p.nombre_paso,
    p.tipo_aprobador,
    r.nombre AS rol,
    ua.nombre_usuario AS usuario_asignado,
    p.estado,
    ud.nombre_usuario AS usuario_decision,
    p.fecha_inicio,
    p.fecha_decision,
    p.comentario
FROM solicitud_paso_aprobacion p
LEFT JOIN rol r ON r.id_rol = p.id_rol
LEFT JOIN usuario ua ON ua.id_usuario = p.id_usuario_asignado
LEFT JOIN usuario ud ON ud.id_usuario = p.id_usuario_decision;

CREATE OR REPLACE VIEW v_bandeja_aprobacion AS
SELECT
    p.id_paso_solicitud,
    p.id_usuario_asignado,
    p.id_rol,
    CASE
        WHEN p.id_solicitud_permiso IS NOT NULL THEN 'PERMISO'
        ELSE 'HORA_EXTRA'
    END AS tipo_solicitud,
    COALESCE(p.id_solicitud_permiso, p.id_solicitud_hora_extra) AS id_solicitud,
    COALESCE(ve_p.nombre_completo, ve_h.nombre_completo) AS solicitante,
    COALESCE(tp.nombre, 'Horas extras') AS tipo_tramite,
    p.numero_paso,
    p.nombre_paso,
    p.tipo_aprobador,
    p.fecha_inicio,
    COALESCE(sp.motivo, he.motivo) AS motivo
FROM solicitud_paso_aprobacion p
LEFT JOIN solicitud_permiso sp ON sp.id_solicitud_permiso = p.id_solicitud_permiso
LEFT JOIN solicitud_hora_extra he ON he.id_solicitud_hora_extra = p.id_solicitud_hora_extra
LEFT JOIN tipo_permiso tp ON tp.id_tipo_permiso = sp.id_tipo_permiso
LEFT JOIN v_empleado ve_p ON ve_p.id_empleado = sp.id_empleado
LEFT JOIN v_empleado ve_h ON ve_h.id_empleado = he.id_empleado
WHERE p.estado = 'EN_CURSO';

CREATE OR REPLACE VIEW v_reporte_asistencia AS
SELECT
    m.id_marcacion,
    ve.codigo_empleado,
    ve.nombre_completo,
    ve.area,
    m.tipo,
    m.fecha,
    m.fecha_hora,
    to_char(m.fecha_hora AT TIME ZONE 'America/Lima', 'HH24:MI:SS') AS hora,
    m.origen,
    m.observacion
FROM marcacion m
JOIN v_empleado ve ON ve.id_empleado = m.id_empleado;

CREATE OR REPLACE VIEW v_trazabilidad_solicitudes AS
SELECT
    h.id_historial,
    CASE
        WHEN h.id_solicitud_permiso IS NOT NULL THEN 'PERMISO'
        ELSE 'HORA_EXTRA'
    END AS tipo_solicitud,
    COALESCE(h.id_solicitud_permiso, h.id_solicitud_hora_extra) AS id_solicitud,
    h.id_paso_solicitud,
    ve.nombre_completo AS trabajador,
    u.nombre_usuario,
    r.nombre AS rol_usuario,
    h.accion,
    h.estado_anterior,
    h.estado_nuevo,
    h.comentario,
    h.fecha_hora
FROM historial_solicitud h
JOIN usuario u ON u.id_usuario = h.id_usuario
JOIN rol r ON r.id_rol = u.id_rol
LEFT JOIN solicitud_permiso sp ON sp.id_solicitud_permiso = h.id_solicitud_permiso
LEFT JOIN solicitud_hora_extra he ON he.id_solicitud_hora_extra = h.id_solicitud_hora_extra
LEFT JOIN v_empleado ve ON ve.id_empleado = COALESCE(sp.id_empleado, he.id_empleado);

-- -----------------------------------------------------------------------------
-- Comentarios de documentación
-- -----------------------------------------------------------------------------
COMMENT ON TABLE empleado IS 'RI-01: Directorio centralizado de trabajadores. id_jefe_inmediato es organigrama, no aprobador de la solicitud.';
COMMENT ON TABLE configuracion_aprobacion IS 'Cabecera del flujo de aprobación por tipo de trámite (vacaciones, salud, horas extras, etc.).';
COMMENT ON TABLE configuracion_aprobacion_detalle IS 'Pasos configurados del flujo: jefe inmediato, un rol o un usuario específico.';
COMMENT ON TABLE solicitud_permiso IS 'RI-02: Pedido de permiso. No almacena aprobador; el circuito se instancia desde la configuración.';
COMMENT ON TABLE solicitud_hora_extra IS 'RI-03: Pedido de horas extras. Usa el mismo motor de aprobación por pasos.';
COMMENT ON TABLE solicitud_paso_aprobacion IS 'Instancia del detalle de configuración: guarda el paso a paso real de cada solicitud.';
COMMENT ON TABLE historial_solicitud IS 'RI-06 / RG-07: Trazabilidad de registro y de cada decisión de paso.';
COMMENT ON TABLE auditoria IS 'RG-14: Acciones relevantes de usuarios sobre el sistema.';
COMMENT ON TABLE carga_masiva IS 'RI-08 / INT-01: Cargas masivas de trabajadores desde Excel.';
COMMENT ON VIEW v_bandeja_aprobacion IS 'Pasos EN_CURSO para armar la bandeja de cada aprobador o rol.';
COMMENT ON VIEW v_reporte_permisos IS 'CU-16: Fuente para reporte de permisos.';
COMMENT ON VIEW v_reporte_horas_extras IS 'CU-17: Fuente para reporte de horas extras.';
COMMENT ON VIEW v_reporte_asistencia IS 'CU-18: Fuente para reporte de asistencia.';
COMMENT ON VIEW v_reporte_usuarios IS 'CU-19: Fuente para reporte de usuarios.';

-- =============================================================================
-- Datos iniciales (catálogos, menú, 3 cuentas, flujos)
-- =============================================================================

INSERT INTO area (nombre, descripcion) VALUES
    ('Gerencia', 'Dirección general de la consultora'),
    ('Recursos Humanos', 'Administración del personal y procesos internos'),
    ('Contabilidad', 'Servicios contables a clientes'),
    ('Tributario', 'Asesoría tributaria y cumplimiento fiscal'),
    ('Administración', 'Soporte administrativo y operaciones internas');

INSERT INTO cargo (nombre, descripcion) VALUES
    ('Gerente General', 'Representante legal y sponsor de la organización'),
    ('Jefe de Recursos Humanos', 'Responsable de la gestión del personal'),
    ('Jefe de Contabilidad', 'Responsable del área contable'),
    ('Contador', 'Ejecución de labores contables'),
    ('Analista Contable', 'Análisis y registro de operaciones contables'),
    ('Asistente Contable', 'Apoyo operativo del área contable'),
    ('Analista Tributario', 'Análisis de obligaciones tributarias'),
    ('Asistente Tributario', 'Apoyo operativo del área tributaria'),
    ('Asistente Administrativo', 'Soporte administrativo interno'),
    ('Asistente de Recepción', 'Atención y apoyo operativo general'),
    ('Jefe de Tributario', 'Responsable del área tributaria'),
    ('Asistente de Recursos Humanos', 'Apoyo operativo de RR. HH.');

INSERT INTO horario_laboral (nombre, hora_ingreso, hora_salida, minutos_refrigerio) VALUES
    ('Jornada administrativa', '09:00', '18:00', 60),
    ('Jornada gerencial', '09:00', '18:30', 60);

INSERT INTO tipo_permiso (codigo, nombre, requiere_sustento) VALUES
    ('PARTICULAR', 'Permiso particular', FALSE),
    ('SALUD', 'Permiso por salud', TRUE),
    ('COMISION', 'Comisión de servicios', FALSE),
    ('CAPACITACION', 'Capacitación', FALSE),
    ('DUELO', 'Permiso por duelo', TRUE),
    ('VACACIONES', 'Vacaciones', FALSE);

INSERT INTO parametro_sistema (clave, valor, descripcion) VALUES
    ('max_horas_extras_diarias', '4', 'Máximo de horas extras permitidas por día (RRN-03)'),
    ('max_horas_extras_semanales', '12', 'Máximo de horas extras permitidas por semana'),
    ('zona_horaria', 'America/Lima', 'Zona horaria oficial de las marcaciones'),
    ('empresa_razon_social', 'Consultora Contable Andina S.A.C.', 'Razón social de la empresa'),
    ('empresa_ruc', '20601234567', 'RUC de demostración');

INSERT INTO rol (codigo, nombre, descripcion) VALUES
    ('ADMIN', 'Administrador', 'Administra usuarios, roles, configuración y auditoría'),
    ('RRHH', 'Responsable de RR. HH.', 'Gestiona personal, supervisa solicitudes y genera reportes'),
    ('APROBADOR', 'Aprobador', 'Revisa, aprueba o rechaza permisos y horas extras'),
    ('EMPLEADO', 'Empleado', 'Registra asistencia, permisos y horas extras propias');

INSERT INTO permiso_funcional (codigo, nombre, modulo) VALUES
    ('PERSONAL_REGISTRAR', 'Registrar trabajador', 'PERSONAL'),
    ('PERSONAL_ACTUALIZAR', 'Actualizar trabajador', 'PERSONAL'),
    ('PERSONAL_CONSULTAR', 'Consultar trabajador', 'PERSONAL'),
    ('PERSONAL_CARGAR_EXCEL', 'Cargar trabajadores desde Excel', 'PERSONAL'),
    ('PERMISO_REGISTRAR', 'Registrar solicitud de permiso', 'PERMISOS'),
    ('PERMISO_CONSULTAR_PROPIO', 'Consultar estado de permiso propio', 'PERMISOS'),
    ('PERMISO_APROBAR', 'Aprobar o rechazar permiso', 'PERMISOS'),
    ('PERMISO_GESTIONAR', 'Gestionar solicitudes de permisos', 'PERMISOS'),
    ('HEXTRA_REGISTRAR', 'Registrar horas extras', 'HORAS_EXTRAS'),
    ('HEXTRA_CONSULTAR_PROPIO', 'Consultar solicitud de horas extras propia', 'HORAS_EXTRAS'),
    ('HEXTRA_APROBAR', 'Aprobar o rechazar horas extras', 'HORAS_EXTRAS'),
    ('HEXTRA_GESTIONAR', 'Supervisar horas extras', 'HORAS_EXTRAS'),
    ('ASISTENCIA_MARCAR', 'Registrar marcación de asistencia', 'ASISTENCIA'),
    ('ASISTENCIA_CONSULTAR_PROPIA', 'Consultar historial de asistencia propio', 'ASISTENCIA'),
    ('ASISTENCIA_GESTIONAR', 'Gestionar registros de asistencia', 'ASISTENCIA'),
    ('USUARIO_GESTIONAR', 'Gestionar usuarios y roles', 'USUARIOS'),
    ('REPORTE_PERMISOS', 'Generar reporte de permisos', 'REPORTES'),
    ('REPORTE_HORAS_EXTRAS', 'Generar reporte de horas extras', 'REPORTES'),
    ('REPORTE_ASISTENCIA', 'Generar reporte de asistencia', 'REPORTES'),
    ('REPORTE_USUARIOS', 'Generar reporte de usuarios', 'REPORTES'),
    ('AUDITORIA_CONSULTAR', 'Consultar auditoría y trazabilidad', 'AUDITORIA'),
    ('FLUJO_CONFIGURAR', 'Configurar flujos de aprobación', 'APROBACIONES');

INSERT INTO rol_permiso (id_rol, id_permiso)
SELECT r.id_rol, p.id_permiso
FROM rol r
CROSS JOIN permiso_funcional p
WHERE r.codigo = 'ADMIN';

INSERT INTO rol_permiso (id_rol, id_permiso)
SELECT r.id_rol, p.id_permiso
FROM rol r
JOIN permiso_funcional p ON p.codigo IN (
    'PERSONAL_REGISTRAR', 'PERSONAL_ACTUALIZAR', 'PERSONAL_CONSULTAR', 'PERSONAL_CARGAR_EXCEL',
    'PERMISO_CONSULTAR_PROPIO', 'PERMISO_GESTIONAR',
    'HEXTRA_CONSULTAR_PROPIO', 'HEXTRA_GESTIONAR',
    'ASISTENCIA_CONSULTAR_PROPIA', 'ASISTENCIA_GESTIONAR',
    'REPORTE_PERMISOS', 'REPORTE_HORAS_EXTRAS', 'REPORTE_ASISTENCIA', 'REPORTE_USUARIOS',
    'AUDITORIA_CONSULTAR', 'FLUJO_CONFIGURAR'
)
WHERE r.codigo = 'RRHH';

INSERT INTO rol_permiso (id_rol, id_permiso)
SELECT r.id_rol, p.id_permiso
FROM rol r
JOIN permiso_funcional p ON p.codigo IN (
    'PERMISO_APROBAR', 'PERMISO_CONSULTAR_PROPIO',
    'HEXTRA_APROBAR', 'HEXTRA_CONSULTAR_PROPIO',
    'ASISTENCIA_MARCAR', 'ASISTENCIA_CONSULTAR_PROPIA'
)
WHERE r.codigo = 'APROBADOR';

INSERT INTO rol_permiso (id_rol, id_permiso)
SELECT r.id_rol, p.id_permiso
FROM rol r
JOIN permiso_funcional p ON p.codigo IN (
    'PERMISO_REGISTRAR', 'PERMISO_CONSULTAR_PROPIO',
    'HEXTRA_REGISTRAR', 'HEXTRA_CONSULTAR_PROPIO',
    'ASISTENCIA_MARCAR', 'ASISTENCIA_CONSULTAR_PROPIA'
)
WHERE r.codigo = 'EMPLEADO';

INSERT INTO menu_item (codigo, etiqueta, ruta, icono, grupo, descripcion, orden) VALUES
    ('INICIO', 'Inicio', '/', 'Home', 'Operación', 'Resumen de la sesión y accesos del perfil.', 10),
    ('BANDEJA', 'Bandeja', '/bandeja', 'Inbox', 'Operación', 'Atender y seguir solicitudes del circuito.', 20),
    ('PERMISOS', 'Permisos', '/permisos', 'ClipboardCheck', 'Operación', 'Registrar y seguir solicitudes de permiso.', 30),
    ('HORAS_EXTRAS', 'Horas extras', '/horas-extras', 'Clock3', 'Operación', 'Registrar y consultar tiempo extra.', 40),
    ('MARCAR', 'Marcar', '/marcar', 'LogIn', 'Operación', 'Registrar entrada o salida del día.', 50),
    ('ASISTENCIA', 'Asistencia', '/asistencia', 'Fingerprint', 'Operación', 'Consultar el historial de marcaciones.', 60),
    ('PERFIL', 'Mi perfil', '/perfil', 'User', 'Operación', 'Ficha de personal y datos de la cuenta.', 70),
    ('PERSONAL', 'Personal', '/empleados', 'Users', 'Administración', 'Directorio, alta y carga de colaboradores.', 80),
    ('USUARIOS', 'Usuarios', '/usuarios', 'UserCog', 'Administración', 'Cuentas de acceso y asignación de perfil.', 90),
    ('MENU', 'Menú', '/menu', 'List', 'Administración', 'Mantenedor de opciones de menú por perfil.', 95),
    ('FLUJOS', 'Flujos', '/flujos', 'GitBranch', 'Administración', 'Circuitos de aprobación.', 100),
    ('REPORTES', 'Reportes', '/reportes', 'FileSpreadsheet', 'Control', 'Exportar permisos, asistencia y personal.', 110),
    ('AUDITORIA', 'Auditoría', '/auditoria', 'Shield', 'Control', 'Trazabilidad de operaciones.', 120);

INSERT INTO menu_rol (id_menu, id_rol)
SELECT m.id_menu, r.id_rol
FROM menu_item m
CROSS JOIN rol r
WHERE r.codigo = 'ADMIN';

INSERT INTO menu_rol (id_menu, id_rol)
SELECT m.id_menu, r.id_rol
FROM menu_item m
JOIN rol r ON r.codigo = 'RRHH'
WHERE m.codigo IN (
    'INICIO', 'BANDEJA', 'PERMISOS', 'HORAS_EXTRAS', 'MARCAR', 'ASISTENCIA', 'PERFIL',
    'PERSONAL', 'USUARIOS', 'FLUJOS', 'REPORTES', 'AUDITORIA'
);

INSERT INTO menu_rol (id_menu, id_rol)
SELECT m.id_menu, r.id_rol
FROM menu_item m
JOIN rol r ON r.codigo = 'APROBADOR'
WHERE m.codigo IN ('INICIO', 'BANDEJA', 'PERMISOS', 'HORAS_EXTRAS', 'MARCAR', 'ASISTENCIA', 'PERFIL');

INSERT INTO menu_rol (id_menu, id_rol)
SELECT m.id_menu, r.id_rol
FROM menu_item m
JOIN rol r ON r.codigo = 'EMPLEADO'
WHERE m.codigo IN ('INICIO', 'BANDEJA', 'PERMISOS', 'HORAS_EXTRAS', 'MARCAR', 'ASISTENCIA', 'PERFIL');

-- Organigrama: Juan (empleado) → Jesús Pantoja (jefe) → Jesús Mechan (admin).
INSERT INTO empleado (
    codigo_empleado, tipo_documento, numero_documento,
    nombres, apellido_paterno, apellido_materno, fecha_nacimiento, sexo,
    correo_institucional, telefono, direccion, fecha_ingreso,
    id_area, id_cargo, id_horario, tipo_contrato, estado, id_jefe_inmediato
) VALUES
    ('AND-001', 'DNI', '70123456', 'Jesús', 'Mechan', 'Gonzales', '1994-03-12', 'M',
     'jesus.mechan@andina.pe', '999111001', 'Av. Javier Prado 1200, San Isidro', '2021-11-08',
     (SELECT id_area FROM area WHERE nombre = 'Gerencia'),
     (SELECT id_cargo FROM cargo WHERE nombre = 'Gerente General'),
     (SELECT id_horario FROM horario_laboral WHERE nombre = 'Jornada gerencial'),
     'PLANILLA', 'ACTIVO', NULL);

INSERT INTO empleado (
    codigo_empleado, tipo_documento, numero_documento,
    nombres, apellido_paterno, apellido_materno, fecha_nacimiento, sexo,
    correo_institucional, telefono, direccion, fecha_ingreso,
    id_area, id_cargo, id_horario, tipo_contrato, estado, id_jefe_inmediato
) VALUES
    ('AND-002', 'DNI', '70234567', 'Jesús', 'Pantoja', 'Pantoja', '1990-07-21', 'M',
     'jesus.pantoja@andina.pe', '999111002', 'Av. Arequipa 890, Lince', '2019-07-10',
     (SELECT id_area FROM area WHERE nombre = 'Contabilidad'),
     (SELECT id_cargo FROM cargo WHERE nombre = 'Jefe de Contabilidad'),
     (SELECT id_horario FROM horario_laboral WHERE nombre = 'Jornada administrativa'),
     'PLANILLA', 'ACTIVO',
     (SELECT id_empleado FROM empleado WHERE codigo_empleado = 'AND-001'));

INSERT INTO empleado (
    codigo_empleado, tipo_documento, numero_documento,
    nombres, apellido_paterno, apellido_materno, fecha_nacimiento, sexo,
    correo_institucional, telefono, direccion, fecha_ingreso,
    id_area, id_cargo, id_horario, tipo_contrato, estado, id_jefe_inmediato
) VALUES
    ('AND-003', 'DNI', '70345678', 'Juan', 'Espinoza', '', '1998-05-04', 'M',
     'juan.espinoza@andina.pe', '999111003', 'Av. Universitaria 880, Los Olivos', '2025-06-02',
     (SELECT id_area FROM area WHERE nombre = 'Contabilidad'),
     (SELECT id_cargo FROM cargo WHERE nombre = 'Asistente Contable'),
     (SELECT id_horario FROM horario_laboral WHERE nombre = 'Jornada administrativa'),
     'PLANILLA', 'ACTIVO',
     (SELECT id_empleado FROM empleado WHERE codigo_empleado = 'AND-002'));

INSERT INTO usuario (id_empleado, id_rol, nombre_usuario, correo, password_hash, activo)
SELECT e.id_empleado, r.id_rol, v.nombre_usuario, e.correo_institucional,
       crypt('Andina2026', gen_salt('bf')), TRUE
FROM (VALUES
    ('AND-001', 'jesus.mechan',  'ADMIN'),
    ('AND-002', 'jesus.pantoja', 'APROBADOR'),
    ('AND-003', 'juan.espinoza', 'EMPLEADO')
) AS v(codigo_empleado, nombre_usuario, codigo_rol)
JOIN empleado e ON e.codigo_empleado = v.codigo_empleado
JOIN rol r ON r.codigo = v.codigo_rol;

INSERT INTO configuracion_aprobacion (codigo, nombre, tipo_origen, id_tipo_permiso, descripcion) VALUES
    ('CFG-PERMISO-DEFAULT', 'Permiso genérico', 'PERMISO', NULL,
     'Flujo por defecto si un tipo de permiso no tiene circuito propio.'),
    ('CFG-PERMISO-PARTICULAR', 'Permiso particular', 'PERMISO',
     (SELECT id_tipo_permiso FROM tipo_permiso WHERE codigo = 'PARTICULAR'),
     'Solo jefe inmediato.'),
    ('CFG-PERMISO-SALUD', 'Permiso por salud', 'PERMISO',
     (SELECT id_tipo_permiso FROM tipo_permiso WHERE codigo = 'SALUD'),
     'Jefe inmediato y luego RR. HH.'),
    ('CFG-PERMISO-VACACIONES', 'Vacaciones', 'PERMISO',
     (SELECT id_tipo_permiso FROM tipo_permiso WHERE codigo = 'VACACIONES'),
     'Jefe inmediato, RR. HH. y Gerencia.'),
    ('CFG-PERMISO-CAPACITACION', 'Capacitación', 'PERMISO',
     (SELECT id_tipo_permiso FROM tipo_permiso WHERE codigo = 'CAPACITACION'),
     'Jefe inmediato y RR. HH.'),
    ('CFG-PERMISO-COMISION', 'Comisión de servicios', 'PERMISO',
     (SELECT id_tipo_permiso FROM tipo_permiso WHERE codigo = 'COMISION'),
     'Jefe inmediato y rol aprobador.'),
    ('CFG-PERMISO-DUELO', 'Permiso por duelo', 'PERMISO',
     (SELECT id_tipo_permiso FROM tipo_permiso WHERE codigo = 'DUELO'),
     'Jefe inmediato y RR. HH.'),
    ('CFG-HEXTRA', 'Horas extras', 'HORA_EXTRA', NULL,
     'Jefe inmediato y validación de RR. HH.');

INSERT INTO configuracion_aprobacion_detalle (
    id_configuracion, numero_paso, nombre_paso, tipo_aprobador, id_rol, id_usuario, es_obligatorio
)
SELECT c.id_configuracion, v.numero_paso, v.nombre_paso, v.tipo_aprobador::tipo_aprobador,
       r.id_rol, u.id_usuario, v.es_obligatorio
FROM (VALUES
    ('CFG-PERMISO-DEFAULT', 1, 'Jefe inmediato', 'JEFE_INMEDIATO', NULL, NULL, TRUE),
    ('CFG-PERMISO-PARTICULAR', 1, 'Jefe inmediato', 'JEFE_INMEDIATO', NULL, NULL, TRUE),
    ('CFG-PERMISO-SALUD', 1, 'Jefe inmediato', 'JEFE_INMEDIATO', NULL, NULL, TRUE),
    ('CFG-PERMISO-SALUD', 2, 'Validación de RR. HH.', 'ROL', 'ADMIN', NULL, TRUE),
    ('CFG-PERMISO-VACACIONES', 1, 'Jefe inmediato', 'JEFE_INMEDIATO', NULL, NULL, TRUE),
    ('CFG-PERMISO-VACACIONES', 2, 'Validación de RR. HH.', 'ROL', 'ADMIN', NULL, TRUE),
    ('CFG-PERMISO-VACACIONES', 3, 'Autorización de Gerencia', 'USUARIO', NULL, 'jesus.mechan', TRUE),
    ('CFG-PERMISO-CAPACITACION', 1, 'Jefe inmediato', 'JEFE_INMEDIATO', NULL, NULL, TRUE),
    ('CFG-PERMISO-CAPACITACION', 2, 'Validación de RR. HH.', 'ROL', 'ADMIN', NULL, TRUE),
    ('CFG-PERMISO-COMISION', 1, 'Jefe inmediato', 'JEFE_INMEDIATO', NULL, NULL, TRUE),
    ('CFG-PERMISO-COMISION', 2, 'Aprobación de jefatura', 'ROL', 'APROBADOR', NULL, TRUE),
    ('CFG-PERMISO-DUELO', 1, 'Jefe inmediato', 'JEFE_INMEDIATO', NULL, NULL, TRUE),
    ('CFG-PERMISO-DUELO', 2, 'Validación de RR. HH.', 'ROL', 'ADMIN', NULL, TRUE),
    ('CFG-HEXTRA', 1, 'Jefe inmediato', 'JEFE_INMEDIATO', NULL, NULL, TRUE),
    ('CFG-HEXTRA', 2, 'Validación de RR. HH.', 'ROL', 'ADMIN', NULL, TRUE)
) AS v(codigo, numero_paso, nombre_paso, tipo_aprobador, codigo_rol, nombre_usuario, es_obligatorio)
JOIN configuracion_aprobacion c ON c.codigo = v.codigo
LEFT JOIN rol r ON r.codigo = v.codigo_rol
LEFT JOIN usuario u ON u.nombre_usuario = v.nombre_usuario;

INSERT INTO auditoria (id_usuario, accion, entidad, id_entidad, detalle)
SELECT id_usuario, 'INICIALIZAR_BD', 'SISTEMA', NULL,
       jsonb_build_object(
           'origen', '01_install.sql',
           'empresa', 'Consultora Contable Andina S.A.C.',
           'colaboradores', 3
       )
FROM usuario
WHERE nombre_usuario = 'jesus.mechan';
