-- =============================================================================
-- Validación del flujo de aprobaciones
-- Consultora Contable Andina S.A.C.
--
-- Requiere que 01_schema.sql y 02_seed.sql ya se hayan ejecutado.
-- Contraseña de todos los usuarios: Andina2026
--
-- pgAdmin:
--   1. Query Tool conectado a rrhh_andina (no a postgres).
--   2. Abre este archivo y pulsa F5 (ejecuta todo el script).
--   3. Pestaña Messages: avisos OK / FALLO de cada caso automático.
--   4. Pestaña Data Output: resultados, usuarios y bandeja [VAL-MANUAL].
--      Si hay varios result sets, recórrelos con las flechas de la grilla.
--   5. Puedes volver a ejecutar este archivo; borra solo las solicitudes [VAL-].
-- =============================================================================

DROP TABLE IF EXISTS validacion_flujo_resultado;

CREATE TABLE validacion_flujo_resultado (
    id_resultado    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caso            VARCHAR(80) NOT NULL,
    detalle         VARCHAR(400),
    ok              BOOLEAN NOT NULL,
    fecha           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION fn_val_registrar(p_caso TEXT, p_ok BOOLEAN, p_detalle TEXT)
RETURNS VOID AS $$
BEGIN
    INSERT INTO validacion_flujo_resultado (caso, detalle, ok)
    VALUES (p_caso, p_detalle, p_ok);

    RAISE NOTICE '% % — %',
        CASE WHEN p_ok THEN 'OK   ' ELSE 'FALLO' END,
        p_caso,
        COALESCE(p_detalle, '');
END;
$$ LANGUAGE plpgsql;

DELETE FROM solicitud_permiso WHERE motivo LIKE '[VAL-%';
DELETE FROM solicitud_hora_extra WHERE motivo LIKE '[VAL-%';

-- -----------------------------------------------------------------------------
-- Caso 1: vacaciones instancia 3 pasos (jefe -> RR. HH. -> Gerencia)
-- -----------------------------------------------------------------------------
DO $$
DECLARE
    v_id INTEGER;
    v_pasos INTEGER;
    v_flujo TEXT;
    v_asignado TEXT;
    v_estado TEXT;
BEGIN
    INSERT INTO solicitud_permiso (id_empleado, id_tipo_permiso, fecha_inicio, fecha_fin, motivo)
    VALUES (
        (SELECT id_empleado FROM empleado WHERE codigo_empleado = 'AND-011'),
        (SELECT id_tipo_permiso FROM tipo_permiso WHERE codigo = 'VACACIONES'),
        '2026-12-01', '2026-12-15',
        '[VAL-AUTO] Vacaciones de Diego León — flujo de 3 pasos'
    )
    RETURNING id_solicitud_permiso INTO v_id;

    SELECT cfg.codigo, COUNT(*)
    INTO v_flujo, v_pasos
    FROM solicitud_permiso sp
    JOIN configuracion_aprobacion cfg ON cfg.id_configuracion = sp.id_configuracion
    JOIN solicitud_paso_aprobacion p ON p.id_solicitud_permiso = sp.id_solicitud_permiso
    WHERE sp.id_solicitud_permiso = v_id
    GROUP BY cfg.codigo;

    PERFORM fn_val_registrar(
        'VACACIONES-INSTANCIA',
        v_flujo = 'CFG-PERMISO-VACACIONES' AND v_pasos = 3,
        format('flujo=%s pasos=%s', v_flujo, v_pasos)
    );

    SELECT u.nombre_usuario, p.estado::TEXT
    INTO v_asignado, v_estado
    FROM solicitud_paso_aprobacion p
    JOIN usuario u ON u.id_usuario = p.id_usuario_asignado
    WHERE p.id_solicitud_permiso = v_id
      AND p.numero_paso = 1;

    PERFORM fn_val_registrar(
        'VACACIONES-PASO1-JEFE',
        v_asignado = 'cmendoza' AND v_estado = 'EN_CURSO',
        format('asignado=%s estado=%s', v_asignado, v_estado)
    );
END;
$$;

-- -----------------------------------------------------------------------------
-- Caso 2: un empleado no autorizado no puede aprobar el paso del jefe
-- -----------------------------------------------------------------------------
DO $$
DECLARE
    v_ok BOOLEAN := FALSE;
    v_id INTEGER;
BEGIN
    SELECT id_solicitud_permiso INTO v_id
    FROM solicitud_permiso
    WHERE motivo = '[VAL-AUTO] Vacaciones de Diego León — flujo de 3 pasos';

    BEGIN
        UPDATE solicitud_paso_aprobacion
        SET estado = 'APROBADO',
            id_usuario_decision = (SELECT id_usuario FROM usuario WHERE nombre_usuario = 'atorres'),
            comentario = 'Intento no autorizado'
        WHERE id_solicitud_permiso = v_id
          AND numero_paso = 1
          AND estado = 'EN_CURSO';

        v_ok := FALSE;
    EXCEPTION
        WHEN OTHERS THEN
            v_ok := TRUE;
    END;

    PERFORM fn_val_registrar(
        'SEGURIDAD-NO-AUTORIZADO',
        v_ok,
        'atorres no debe poder aprobar el paso del jefe de Diego'
    );
END;
$$;

-- -----------------------------------------------------------------------------
-- Caso 3: el jefe aprueba y el flujo avanza a RR. HH.
-- -----------------------------------------------------------------------------
DO $$
DECLARE
    v_id INTEGER;
    v_paso2 TEXT;
    v_cabecera TEXT;
BEGIN
    SELECT id_solicitud_permiso INTO v_id
    FROM solicitud_permiso
    WHERE motivo = '[VAL-AUTO] Vacaciones de Diego León — flujo de 3 pasos';

    UPDATE solicitud_paso_aprobacion
    SET estado = 'APROBADO',
        id_usuario_decision = (SELECT id_usuario FROM usuario WHERE nombre_usuario = 'cmendoza'),
        comentario = 'Jefe de Contabilidad da el visto bueno.'
    WHERE id_solicitud_permiso = v_id
      AND numero_paso = 1
      AND estado = 'EN_CURSO';

    SELECT estado::TEXT INTO v_paso2
    FROM solicitud_paso_aprobacion
    WHERE id_solicitud_permiso = v_id
      AND numero_paso = 2;

    SELECT estado::TEXT INTO v_cabecera
    FROM solicitud_permiso
    WHERE id_solicitud_permiso = v_id;

    PERFORM fn_val_registrar(
        'VACACIONES-AVANCE-RRHH',
        v_paso2 = 'EN_CURSO' AND v_cabecera = 'PENDIENTE',
        format('paso2=%s solicitud=%s', v_paso2, v_cabecera)
    );
END;
$$;

-- -----------------------------------------------------------------------------
-- Caso 4: cualquier usuario con rol RR. HH. puede tomar el segundo paso
-- -----------------------------------------------------------------------------
DO $$
DECLARE
    v_id INTEGER;
    v_paso3 TEXT;
    v_asignado TEXT;
BEGIN
    SELECT id_solicitud_permiso INTO v_id
    FROM solicitud_permiso
    WHERE motivo = '[VAL-AUTO] Vacaciones de Diego León — flujo de 3 pasos';

    UPDATE solicitud_paso_aprobacion
    SET estado = 'APROBADO',
        id_usuario_decision = (SELECT id_usuario FROM usuario WHERE nombre_usuario = 'csilva'),
        comentario = 'RR. HH. valida el saldo de vacaciones.'
    WHERE id_solicitud_permiso = v_id
      AND numero_paso = 2
      AND estado = 'EN_CURSO';

    SELECT p.estado::TEXT, u.nombre_usuario
    INTO v_paso3, v_asignado
    FROM solicitud_paso_aprobacion p
    JOIN usuario u ON u.id_usuario = p.id_usuario_asignado
    WHERE p.id_solicitud_permiso = v_id
      AND p.numero_paso = 3;

    PERFORM fn_val_registrar(
        'VACACIONES-AVANCE-GERENCIA',
        v_paso3 = 'EN_CURSO' AND v_asignado = 'rsalas',
        format('paso3=%s asignado=%s (aprobó csilva, no mquispe)', v_paso3, v_asignado)
    );
END;
$$;

-- -----------------------------------------------------------------------------
-- Caso 5: Gerencia cierra el flujo y la solicitud queda APROBADO
-- -----------------------------------------------------------------------------
DO $$
DECLARE
    v_id INTEGER;
    v_estado TEXT;
    v_aprobados INTEGER;
BEGIN
    SELECT id_solicitud_permiso INTO v_id
    FROM solicitud_permiso
    WHERE motivo = '[VAL-AUTO] Vacaciones de Diego León — flujo de 3 pasos';

    UPDATE solicitud_paso_aprobacion
    SET estado = 'APROBADO',
        id_usuario_decision = (SELECT id_usuario FROM usuario WHERE nombre_usuario = 'rsalas'),
        comentario = 'Gerencia autoriza el goce de vacaciones.'
    WHERE id_solicitud_permiso = v_id
      AND numero_paso = 3
      AND estado = 'EN_CURSO';

    SELECT estado::TEXT INTO v_estado
    FROM solicitud_permiso
    WHERE id_solicitud_permiso = v_id;

    SELECT COUNT(*) INTO v_aprobados
    FROM solicitud_paso_aprobacion
    WHERE id_solicitud_permiso = v_id
      AND estado = 'APROBADO';

    PERFORM fn_val_registrar(
        'VACACIONES-CIERRE',
        v_estado = 'APROBADO' AND v_aprobados = 3,
        format('solicitud=%s pasos_aprobados=%s', v_estado, v_aprobados)
    );
END;
$$;

-- -----------------------------------------------------------------------------
-- Caso 6: rechazo en el primer paso omite el resto
-- -----------------------------------------------------------------------------
DO $$
DECLARE
    v_id INTEGER;
    v_estado TEXT;
    v_omitidos INTEGER;
BEGIN
    INSERT INTO solicitud_permiso (id_empleado, id_tipo_permiso, fecha_inicio, fecha_fin, motivo)
    VALUES (
        (SELECT id_empleado FROM empleado WHERE codigo_empleado = 'AND-015'),
        (SELECT id_tipo_permiso FROM tipo_permiso WHERE codigo = 'SALUD'),
        '2026-09-21', '2026-09-22',
        '[VAL-AUTO] Salud de Bruno Aguilar — rechazo del jefe'
    )
    RETURNING id_solicitud_permiso INTO v_id;

    UPDATE solicitud_paso_aprobacion
    SET estado = 'RECHAZADO',
        id_usuario_decision = (SELECT id_usuario FROM usuario WHERE nombre_usuario = 'sparedes'),
        comentario = 'Rechazado: debe regularizar asistencia primero.'
    WHERE id_solicitud_permiso = v_id
      AND numero_paso = 1
      AND estado = 'EN_CURSO';

    SELECT estado::TEXT INTO v_estado
    FROM solicitud_permiso
    WHERE id_solicitud_permiso = v_id;

    SELECT COUNT(*) INTO v_omitidos
    FROM solicitud_paso_aprobacion
    WHERE id_solicitud_permiso = v_id
      AND estado = 'OMITIDO';

    PERFORM fn_val_registrar(
        'SALUD-RECHAZO-OMITE',
        v_estado = 'RECHAZADO' AND v_omitidos = 1,
        format('solicitud=%s pasos_omitidos=%s', v_estado, v_omitidos)
    );
END;
$$;

-- -----------------------------------------------------------------------------
-- Caso 7: horas extras instancia jefe + RR. HH.
-- -----------------------------------------------------------------------------
DO $$
DECLARE
    v_id INTEGER;
    v_flujo TEXT;
    v_pasos INTEGER;
BEGIN
    INSERT INTO solicitud_hora_extra (id_empleado, fecha, hora_inicio, hora_fin, cantidad_horas, motivo)
    VALUES (
        (SELECT id_empleado FROM empleado WHERE codigo_empleado = 'AND-013'),
        '2026-09-08', '18:00', '20:30', 2.50,
        '[VAL-AUTO] Horas extras de Valeria — instancia de 2 pasos'
    )
    RETURNING id_solicitud_hora_extra INTO v_id;

    SELECT cfg.codigo, COUNT(*)
    INTO v_flujo, v_pasos
    FROM solicitud_hora_extra he
    JOIN configuracion_aprobacion cfg ON cfg.id_configuracion = he.id_configuracion
    JOIN solicitud_paso_aprobacion p ON p.id_solicitud_hora_extra = he.id_solicitud_hora_extra
    WHERE he.id_solicitud_hora_extra = v_id
    GROUP BY cfg.codigo;

    PERFORM fn_val_registrar(
        'HEXTRA-INSTANCIA',
        v_flujo = 'CFG-HEXTRA' AND v_pasos = 2,
        format('flujo=%s pasos=%s', v_flujo, v_pasos)
    );

    UPDATE solicitud_paso_aprobacion
    SET estado = 'APROBADO',
        id_usuario_decision = (SELECT id_usuario FROM usuario WHERE nombre_usuario = 'sparedes'),
        comentario = 'Jefa tributaria confirma la jornada adicional.'
    WHERE id_solicitud_hora_extra = v_id
      AND numero_paso = 1
      AND estado = 'EN_CURSO';

    UPDATE solicitud_paso_aprobacion
    SET estado = 'APROBADO',
        id_usuario_decision = (SELECT id_usuario FROM usuario WHERE nombre_usuario = 'mquispe'),
        comentario = 'RR. HH. valida el tope semanal.'
    WHERE id_solicitud_hora_extra = v_id
      AND numero_paso = 2
      AND estado = 'EN_CURSO';

    PERFORM fn_val_registrar(
        'HEXTRA-CIERRE',
        EXISTS (
            SELECT 1 FROM solicitud_hora_extra
            WHERE id_solicitud_hora_extra = v_id
              AND estado = 'APROBADO'
        ),
        'Valeria queda con horas extras aprobadas por jefe y RR. HH.'
    );
END;
$$;

-- -----------------------------------------------------------------------------
-- Casos MANUALES: quedan EN_CURSO para que valides tú el flujo
-- -----------------------------------------------------------------------------
INSERT INTO solicitud_permiso (id_empleado, id_tipo_permiso, fecha_inicio, fecha_fin, motivo) VALUES
    ((SELECT id_empleado FROM empleado WHERE codigo_empleado = 'AND-016'),
     (SELECT id_tipo_permiso FROM tipo_permiso WHERE codigo = 'VACACIONES'),
     '2026-10-05', '2026-10-16',
     '[VAL-MANUAL] Vacaciones de Lucía — tú apruebas como cmendoza, luego csilva/mquispe, luego rsalas'),
    ((SELECT id_empleado FROM empleado WHERE codigo_empleado = 'AND-017'),
     (SELECT id_tipo_permiso FROM tipo_permiso WHERE codigo = 'PARTICULAR'),
     '2026-09-18', '2026-09-18',
     '[VAL-MANUAL] Particular de Héctor — tú apruebas o rechazas como mquispe'),
    ((SELECT id_empleado FROM empleado WHERE codigo_empleado = 'AND-013'),
     (SELECT id_tipo_permiso FROM tipo_permiso WHERE codigo = 'COMISION'),
     '2026-09-24', '2026-09-24',
     '[VAL-MANUAL] Comisión de Valeria — tú apruebas como sparedes y luego como cmendoza/rsalas/sparedes (rol APROBADOR)');

INSERT INTO solicitud_hora_extra (id_empleado, fecha, hora_inicio, hora_fin, cantidad_horas, motivo)
VALUES (
    (SELECT id_empleado FROM empleado WHERE codigo_empleado = 'AND-016'),
    '2026-09-09', '18:00', '21:00', 3.00,
    '[VAL-MANUAL] Horas extras de Lucía — tú apruebas como cmendoza y luego como mquispe/csilva'
);

-- Salud de Lucía: el jefe ya dio el visto bueno; queda en RR. HH.
INSERT INTO solicitud_permiso (id_empleado, id_tipo_permiso, fecha_inicio, fecha_fin, motivo)
VALUES (
    (SELECT id_empleado FROM empleado WHERE codigo_empleado = 'AND-016'),
    (SELECT id_tipo_permiso FROM tipo_permiso WHERE codigo = 'SALUD'),
    '2026-09-14', '2026-09-15',
    '[VAL-MANUAL] Salud de Lucía — pendiente de RR. HH. (mquispe o csilva)'
);

UPDATE solicitud_paso_aprobacion p
SET estado = 'APROBADO',
    id_usuario_decision = (SELECT id_usuario FROM usuario WHERE nombre_usuario = 'cmendoza'),
    comentario = 'Jefe adelanta el primer paso para que valides el segundo.'
FROM solicitud_permiso sp
WHERE p.id_solicitud_permiso = sp.id_solicitud_permiso
  AND sp.motivo = '[VAL-MANUAL] Salud de Lucía — pendiente de RR. HH. (mquispe o csilva)'
  AND p.numero_paso = 1
  AND p.estado = 'EN_CURSO';

DO $$
DECLARE
    v_pendientes INTEGER;
    v_fallos INTEGER;
BEGIN
    SELECT COUNT(*) INTO v_pendientes
    FROM v_bandeja_aprobacion
    WHERE motivo LIKE '[VAL-MANUAL]%';

    PERFORM fn_val_registrar(
        'BANDEJA-MANUAL',
        v_pendientes >= 4,
        format('casos manuales en bandeja=%s', v_pendientes)
    );

    SELECT COUNT(*) INTO v_fallos
    FROM validacion_flujo_resultado
    WHERE NOT ok;

    IF v_fallos > 0 THEN
        RAISE EXCEPTION 'La validación del flujo falló en % caso(s). Revisa validacion_flujo_resultado.', v_fallos;
    END IF;
END;
$$;

-- -----------------------------------------------------------------------------
-- Guía para validar tú el flujo
-- -----------------------------------------------------------------------------
SELECT
    CASE WHEN ok THEN 'OK' ELSE 'FALLO' END AS resultado,
    caso,
    detalle
FROM validacion_flujo_resultado
ORDER BY id_resultado;

SELECT
    'Andina2026' AS password,
    u.nombre_usuario,
    r.nombre AS rol,
    ve.nombre_completo,
    ve.area,
    ve.cargo,
    ve.jefe_inmediato
FROM usuario u
JOIN rol r ON r.id_rol = u.id_rol
JOIN v_empleado ve ON ve.id_empleado = u.id_empleado
ORDER BY u.nombre_usuario;

SELECT
    b.tipo_solicitud,
    b.id_solicitud,
    b.solicitante,
    b.tipo_tramite,
    b.numero_paso,
    b.nombre_paso,
    b.tipo_aprobador,
    COALESCE(ua.nombre_usuario, r.nombre) AS quien_debe_aprobar,
    b.motivo
FROM v_bandeja_aprobacion b
LEFT JOIN usuario ua ON ua.id_usuario = b.id_usuario_asignado
LEFT JOIN rol r ON r.id_rol = b.id_rol
WHERE b.motivo LIKE '[VAL-MANUAL]%'
ORDER BY b.tipo_solicitud, b.id_solicitud, b.numero_paso;

-- Ejemplo para aprobar el paso en curso de Lucía (vacaciones) como cmendoza:
-- UPDATE solicitud_paso_aprobacion
-- SET estado = 'APROBADO',
--     id_usuario_decision = (SELECT id_usuario FROM usuario WHERE nombre_usuario = 'cmendoza'),
--     comentario = 'Aprobado por jefe'
-- WHERE id_paso_solicitud = <id de v_bandeja_aprobacion>;
