-- Ejecutar en pgAdmin sobre rrhh_andina si la base ya existe y no quieres rerun de 01.
CREATE TABLE IF NOT EXISTS refresh_token (
    id_refresh_token    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario          INTEGER NOT NULL REFERENCES usuario (id_usuario) ON DELETE CASCADE,
    token               VARCHAR(200) NOT NULL,
    fecha_expiracion    TIMESTAMPTZ NOT NULL,
    revocado            BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_refresh_token UNIQUE (token)
);

CREATE INDEX IF NOT EXISTS ix_refresh_token_usuario ON refresh_token (id_usuario, revocado);
