-- Menú dinámico asociado a cada perfil (rol).
-- Seguro de ejecutar sobre una base ya existente.

CREATE TABLE IF NOT EXISTS menu_item (
    id_menu         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(40) NOT NULL,
    etiqueta        VARCHAR(80) NOT NULL,
    ruta            VARCHAR(120) NOT NULL,
    icono           VARCHAR(40) NOT NULL,
    grupo           VARCHAR(40) NOT NULL,
    descripcion     VARCHAR(200),
    orden           INTEGER NOT NULL DEFAULT 0,
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_menu_item_codigo UNIQUE (codigo)
);

CREATE TABLE IF NOT EXISTS menu_rol (
    id_menu INTEGER NOT NULL REFERENCES menu_item (id_menu) ON DELETE CASCADE,
    id_rol  INTEGER NOT NULL REFERENCES rol (id_rol) ON DELETE CASCADE,
    PRIMARY KEY (id_menu, id_rol)
);

INSERT INTO menu_item (codigo, etiqueta, ruta, icono, grupo, descripcion, orden)
SELECT v.codigo, v.etiqueta, v.ruta, v.icono, v.grupo, v.descripcion, v.orden
FROM (VALUES
    ('INICIO', 'Inicio', '/', 'Home', 'Operación', 'Resumen de la sesión y accesos del perfil.', 10),
    ('BANDEJA', 'Bandeja', '/bandeja', 'Inbox', 'Operación', 'Aprobar o rechazar pasos en curso.', 20),
    ('PERMISOS', 'Permisos', '/permisos', 'ClipboardCheck', 'Operación', 'Registrar y seguir solicitudes de permiso.', 30),
    ('HORAS_EXTRAS', 'Horas extras', '/horas-extras', 'Clock3', 'Operación', 'Registrar y consultar tiempo extra.', 40),
    ('MARCAR', 'Marcar', '/marcar', 'LogIn', 'Operación', 'Registrar entrada o salida del día.', 50),
    ('ASISTENCIA', 'Asistencia', '/asistencia', 'Fingerprint', 'Operación', 'Consultar el historial de marcaciones.', 60),
    ('PERFIL', 'Mi perfil', '/perfil', 'User', 'Operación', 'Ficha de personal y datos de la cuenta.', 70),
    ('PERSONAL', 'Personal', '/empleados', 'Users', 'Administración', 'Directorio, alta y carga de colaboradores.', 80),
    ('USUARIOS', 'Usuarios', '/usuarios', 'UserCog', 'Administración', 'Cuentas de acceso y asignación de perfil.', 90),
    ('MENU', 'Menú', '/menu', 'List', 'Administración', 'Mantenedor de opciones de menú por perfil.', 95),
    ('FLUJOS', 'Flujos', '/flujos', 'GitBranch', 'Administración', 'Circuitos de aprobación.', 100),
    ('REPORTES', 'Reportes', '/reportes', 'FileSpreadsheet', 'Control', 'Exportar permisos, asistencia y personal.', 110),
    ('AUDITORIA', 'Auditoría', '/auditoria', 'Shield', 'Control', 'Trazabilidad de operaciones.', 120)
) AS v(codigo, etiqueta, ruta, icono, grupo, descripcion, orden)
WHERE NOT EXISTS (SELECT 1 FROM menu_item m WHERE m.codigo = v.codigo);

INSERT INTO menu_rol (id_menu, id_rol)
SELECT m.id_menu, r.id_rol
FROM menu_item m
CROSS JOIN rol r
WHERE r.codigo = 'ADMIN'
  AND NOT EXISTS (SELECT 1 FROM menu_rol x WHERE x.id_menu = m.id_menu AND x.id_rol = r.id_rol);

INSERT INTO menu_rol (id_menu, id_rol)
SELECT m.id_menu, r.id_rol
FROM menu_item m
JOIN rol r ON r.codigo = 'RRHH'
WHERE m.codigo IN (
    'INICIO', 'BANDEJA', 'PERMISOS', 'HORAS_EXTRAS', 'MARCAR', 'ASISTENCIA', 'PERFIL',
    'PERSONAL', 'USUARIOS', 'FLUJOS', 'REPORTES', 'AUDITORIA'
)
  AND NOT EXISTS (SELECT 1 FROM menu_rol x WHERE x.id_menu = m.id_menu AND x.id_rol = r.id_rol);

INSERT INTO menu_rol (id_menu, id_rol)
SELECT m.id_menu, r.id_rol
FROM menu_item m
JOIN rol r ON r.codigo = 'APROBADOR'
WHERE m.codigo IN ('INICIO', 'BANDEJA', 'PERMISOS', 'HORAS_EXTRAS', 'MARCAR', 'ASISTENCIA', 'PERFIL')
  AND NOT EXISTS (SELECT 1 FROM menu_rol x WHERE x.id_menu = m.id_menu AND x.id_rol = r.id_rol);

INSERT INTO menu_rol (id_menu, id_rol)
SELECT m.id_menu, r.id_rol
FROM menu_item m
JOIN rol r ON r.codigo = 'EMPLEADO'
WHERE m.codigo IN ('INICIO', 'PERMISOS', 'HORAS_EXTRAS', 'MARCAR', 'ASISTENCIA', 'PERFIL')
  AND NOT EXISTS (SELECT 1 FROM menu_rol x WHERE x.id_menu = m.id_menu AND x.id_rol = r.id_rol);
