server:
  port: 8080

spring:
  application:
    name: rrhh-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/rrhh_andina}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: America/Lima
        type:
          preferred_enum_jdbc_type: NAMED_ENUM
    show-sql: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
  api-docs:
    path: /v3/api-docs

app:
  jwt:
    secret: ${JWT_SECRET:AndinaRRHH2026JwtSecretClaveSuperSeguraDeAlMenos64Caracteres!!}
    access-expiration-ms: 900000
    refresh-expiration-ms: 604800000
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:4200,http://localhost:5173,http://localhost:3000}
