-- =============================================================================
-- 06: configuración dinámica.
-- Catálogos, reglas de planilla, valores con vigencia, permisos funcionales,
-- datos de empresa y límites operativos pasan a la base de datos.
--
-- Idempotente. El backend lo ejecuta al iniciar (MenuSchemaInitializer) después
-- de db/schema.sql. También puede ejecutarse a mano en pgAdmin.
-- =============================================================================

CREATE TABLE IF NOT EXISTS script_aplicado (
    codigo          VARCHAR(80) PRIMARY KEY,
    fecha_aplicacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- 1. Parámetros: ámbito de exposición y valores con vigencia
--    PUBLICO: se entrega sin sesión (login, marca).
--    SESION:  se entrega a cualquier usuario autenticado.
--    PRIVADO: solo se ve desde Maestros.
-- -----------------------------------------------------------------------------
ALTER TABLE parametro_sistema ADD COLUMN IF NOT EXISTS ambito VARCHAR(10) NOT NULL DEFAULT 'SESION';
ALTER TABLE parametro_sistema DROP CONSTRAINT IF EXISTS ck_parametro_ambito;
ALTER TABLE parametro_sistema ADD CONSTRAINT ck_parametro_ambito CHECK (ambito IN ('PUBLICO', 'SESION', 'PRIVADO'));

CREATE TABLE IF NOT EXISTS parametro_vigencia (
    id_vigencia     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clave           VARCHAR(80) NOT NULL,
    valor           VARCHAR(200) NOT NULL,
    vigente_desde   DATE NOT NULL,
    descripcion     VARCHAR(300),
    CONSTRAINT uq_parametro_vigencia UNIQUE (clave, vigente_desde)
);

COMMENT ON TABLE parametro_vigencia IS
    'Valores que cambian por norma (RMV, UIT, RAM). Se usa el registro con mayor vigente_desde <= fecha; si no hay, parametro_sistema.';

INSERT INTO parametro_vigencia (clave, valor, vigente_desde, descripcion) VALUES
    ('rmv', '1130', DATE '2025-01-01', 'RMV (DS 006-2024-TR)'),
    ('rmv', '1230', DATE '2026-10-01', 'RMV primer tramo (DS 015-2026-TR)'),
    ('rmv', '1300', DATE '2027-01-01', 'RMV segundo tramo previsto (DS 015-2026-TR)'),
    ('uit', '5350', DATE '2025-01-01', 'UIT 2025'),
    ('uit', '5500', DATE '2026-01-01', 'UIT 2026 (DS 301-2025-EF)'),
    ('ram', '12209.11', DATE '2026-01-01', 'RAM ene-mar 2026 (SBS)'),
    ('ram', '12672.65', DATE '2026-04-01', 'RAM desde abr 2026 (SBS)')
ON CONFLICT (clave, vigente_desde) DO NOTHING;

INSERT INTO parametro_sistema (clave, valor, descripcion, ambito) VALUES
    ('app_nombre', 'Sistema RR. HH.', 'Nombre de la aplicación (título, login)', 'PUBLICO'),
    ('empresa_razon_social', 'Consultora Contable Andina S.A.C.', 'Razón social de la empresa', 'PUBLICO'),
    ('empresa_nombre_comercial', 'Consultora Andina', 'Nombre corto para cabeceras y pies de página', 'PUBLICO'),
    ('empresa_siglas', 'CA', 'Siglas del logotipo', 'PUBLICO'),
    ('empresa_ruc', '20601234567', 'RUC de la empresa', 'PUBLICO'),
    ('empresa_direccion', 'Av. Javier Prado 1200, San Isidro, Lima', 'Dirección fiscal', 'PUBLICO'),
    ('empresa_dominio_correo', 'andina.pe', 'Dominio del correo institucional', 'SESION'),
    ('zona_horaria', 'America/Lima', 'Zona horaria oficial de las marcaciones', 'PUBLICO'),
    ('locale', 'es-PE', 'Idioma y formato regional (fechas, números)', 'PUBLICO'),
    ('moneda_codigo', 'PEN', 'Código ISO de la moneda', 'PUBLICO'),
    ('moneda_simbolo', 'S/', 'Símbolo de la moneda', 'PUBLICO'),
    ('moneda_nombre', 'SOLES', 'Nombre de la moneda en letras (boleta)', 'SESION'),
    ('rmv', '1130', 'RMV de respaldo si no hay vigencia aplicable', 'SESION'),
    ('uit', '5500', 'UIT de respaldo si no hay vigencia aplicable', 'SESION'),
    ('ram', '12672.65', 'RAM de respaldo si no hay vigencia aplicable', 'SESION'),
    ('dias_mes_computable', '30', 'Días del mes laboral para prorrateo y ausencias', 'SESION'),
    ('meses_semestre', '6', 'Meses de un semestre (gratificación y CTS)', 'SESION'),
    ('meses_anio', '12', 'Meses del año (CTS y retención anual)', 'SESION'),
    ('meses_proyeccion_quinta', '14', 'Remuneraciones proyectadas al año para 5ta categoría', 'SESION'),
    ('uit_deduccion_quinta', '7', 'UIT deducibles de la renta anual de 5ta categoría', 'SESION'),
    ('subvencion_practicante_minima', '1025', 'Subvención del practicante cuando el contrato no indica monto', 'SESION'),
    ('remuneracion_maxima', '99999', 'Tope de remuneración que se puede registrar en un contrato', 'SESION'),
    ('codigo_empleado_prefijo', 'AND', 'Prefijo del código de trabajador', 'SESION'),
    ('codigo_empleado_digitos', '3', 'Dígitos del correlativo del código de trabajador', 'SESION'),
    ('codigo_contrato_prefijo', 'CTR', 'Prefijo del código de contrato', 'SESION'),
    ('codigo_convocatoria_prefijo', 'CONV', 'Prefijo del código de convocatoria', 'SESION'),
    ('codigo_asiento_prefijo', 'ASI', 'Prefijo del código de asiento contable', 'SESION'),
    ('codigo_boleta_prefijo', 'AND', 'Prefijo del número de boleta', 'SESION'),
    ('codigo_correlativo_digitos', '3', 'Dígitos de los correlativos de contrato y convocatoria', 'SESION'),
    ('hora_extra_min_solicitud', '0.5', 'Horas mínimas por solicitud de horas extras', 'SESION'),
    ('hora_extra_max_solicitud', '8', 'Horas máximas por solicitud de horas extras', 'SESION'),
    ('hora_extra_fraccion', '0.5', 'Fracción de redondeo de horas extras', 'SESION'),
    ('dias_laborables', '1,2,3,4,5', 'Días laborables ISO (1 = lunes … 7 = domingo) para marcar asistencia', 'SESION'),
    ('minutos_tolerancia_tardanza', '30', 'Minutos de tolerancia sobre la hora de ingreso del horario', 'SESION'),
    ('motivo_min_caracteres', '5', 'Caracteres mínimos del motivo de una solicitud', 'SESION'),
    ('comentario_rechazo_min_caracteres', '3', 'Caracteres mínimos del comentario al rechazar', 'SESION'),
    ('password_min_longitud', '6', 'Longitud mínima de contraseña', 'SESION'),
    ('password_inicial', 'Andina2026', 'Contraseña inicial de cuentas nuevas', 'PRIVADO'),
    ('rol_por_defecto', 'EMPLEADO', 'Código del perfil sugerido al crear una cuenta', 'SESION'),
    ('evaluacion_escala_min', '1', 'Puntaje mínimo por criterio de desempeño', 'SESION'),
    ('evaluacion_escala_max', '5', 'Puntaje máximo por criterio de desempeño', 'SESION'),
    ('postulante_puntaje_max', '100', 'Puntaje máximo de un postulante', 'SESION'),
    ('horario_refrigerio_defecto', '60', 'Minutos de refrigerio sugeridos para un horario nuevo', 'SESION'),
    ('horario_refrigerio_max', '180', 'Máximo de minutos de refrigerio en un horario', 'SESION'),
    ('asistencia_dias_historial', '15', 'Días de historial de asistencia cuando no se indica rango', 'SESION'),
    ('notificaciones_limite', '40', 'Notificaciones que se muestran por usuario', 'SESION'),
    ('dias_vacaciones_mensuales', '1.5', 'Días de vacaciones que se acumulan por mes completo', 'SESION'),
    ('tasa_essalud', '0.09', 'Aporte EsSalud del empleador (Ley 26790)', 'SESION'),
    ('tasa_onp', '0.13', 'Descuento ONP del trabajador (D. Ley 19990)', 'SESION'),
    ('horas_mensuales_base', '240', 'Horas mensuales para valorizar la hora ordinaria', 'SESION'),
    ('tasa_asignacion_familiar', '0.10', 'Asignación familiar = tasa × RMV (Ley 25129)', 'SESION'),
    ('horas_extra_tramo1', '2', 'Horas del primer tramo de sobretasa', 'SESION'),
    ('tasa_hora_extra_tramo1', '1.25', 'Multiplicador de las primeras horas extras (D. Leg. 854)', 'SESION'),
    ('tasa_hora_extra_tramo2', '1.35', 'Multiplicador de las horas extras restantes (D. Leg. 854)', 'SESION'),
    ('tasa_afp_aporte', '0.10', 'Aporte obligatorio al fondo AFP', 'SESION'),
    ('tasa_afp_seguro', '0.0137', 'Prima de seguro previsional AFP (tope RAM)', 'SESION'),
    ('max_horas_extras_diarias', '4', 'Máximo de horas extras por día', 'SESION'),
    ('max_horas_extras_semanales', '12', 'Máximo de horas extras por semana', 'SESION'),
    ('moneda_nombre_singular', 'SOL', 'Nombre de la moneda en singular (boleta)', 'SESION'),
    ('formato_fecha', 'dd/MM/yyyy', 'Formato de fecha de documentos (patrón Java)', 'PUBLICO'),
    ('boleta_nota_pie', 'Documento interno del sistema de RR. HH. No sustituye la boleta electrónica SUNAT si el empleador debe emitirla.', 'Nota al pie de la boleta de pago', 'SESION')
ON CONFLICT (clave) DO NOTHING;

INSERT INTO cuenta_contable (codigo, nombre, uso, naturaleza)
SELECT v.codigo, v.nombre, v.uso, v.naturaleza
FROM (VALUES
    ('4033', 'AFP por pagar', 'AFP_POR_PAGAR', 'PASIVO'),
    ('4017', 'Renta 5ta categoría por pagar', 'QUINTA_POR_PAGAR', 'PASIVO')
) AS v(codigo, nombre, uso, naturaleza)
WHERE NOT EXISTS (SELECT 1 FROM cuenta_contable c WHERE c.uso = v.uso)
  AND NOT EXISTS (SELECT 1 FROM cuenta_contable c WHERE c.codigo = v.codigo);

-- -----------------------------------------------------------------------------
-- 2. Catálogos de valores (etiqueta, color, orden, valor por defecto, regla)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS catalogo_tipo (
    codigo          VARCHAR(40) PRIMARY KEY,
    nombre          VARCHAR(120) NOT NULL,
    extensible      BOOLEAN NOT NULL DEFAULT FALSE
);

COMMENT ON COLUMN catalogo_tipo.extensible IS
    'TRUE: se pueden crear valores nuevos desde Maestros. FALSE: los códigos los usa la lógica; solo se editan etiqueta, color y orden.';

CREATE TABLE IF NOT EXISTS catalogo_valor (
    id_valor        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo            VARCHAR(40) NOT NULL REFERENCES catalogo_tipo (codigo),
    codigo          VARCHAR(40) NOT NULL,
    nombre          VARCHAR(120) NOT NULL,
    tono            VARCHAR(20),
    orden           INTEGER NOT NULL DEFAULT 0,
    por_defecto     BOOLEAN NOT NULL DEFAULT FALSE,
    regla           VARCHAR(200),
    mensaje_regla   VARCHAR(200),
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_catalogo_valor UNIQUE (tipo, codigo),
    CONSTRAINT ck_catalogo_tono CHECK (tono IS NULL OR tono IN ('ok', 'warn', 'danger', 'info', 'neutral', 'muted'))
);

INSERT INTO catalogo_tipo (codigo, nombre, extensible) VALUES
    ('TIPO_DOCUMENTO', 'Tipo de documento', FALSE),
    ('SEXO', 'Sexo', FALSE),
    ('TIPO_CONTRATO', 'Tipo de contrato', FALSE),
    ('ESTADO_EMPLEADO', 'Estado del trabajador', FALSE),
    ('MODALIDAD_CONTRATO', 'Modalidad de contrato', FALSE),
    ('REGIMEN_PENSIONARIO', 'Régimen pensionario', FALSE),
    ('ESTADO_CONTRATO', 'Estado del contrato', FALSE),
    ('ESTADO_SOLICITUD', 'Estado de solicitud', FALSE),
    ('ESTADO_PASO', 'Estado del paso de aprobación', FALSE),
    ('TIPO_MARCACION', 'Tipo de marcación', FALSE),
    ('ORIGEN_MARCACION', 'Origen de marcación', FALSE),
    ('ESTADO_PLANILLA', 'Estado de planilla', FALSE),
    ('ESTADO_ASIENTO', 'Estado de asiento', FALSE),
    ('ESTADO_EVALUACION', 'Estado de evaluación', FALSE),
    ('ESTADO_CONVOCATORIA', 'Estado de convocatoria', FALSE),
    ('ESTADO_POSTULACION', 'Estado de postulación', FALSE),
    ('TIPO_ORIGEN_FLUJO', 'Trámite del flujo', FALSE),
    ('TIPO_APROBADOR', 'Tipo de aprobador', FALSE),
    ('TIPO_REPORTE', 'Tipo de reporte', FALSE),
    ('TIPO_NOTIFICACION', 'Tipo de notificación', FALSE),
    ('USO_CUENTA', 'Uso de cuenta en el asiento de planilla', FALSE),
    ('NATURALEZA_CUENTA', 'Naturaleza de cuenta', TRUE),
    ('GRUPO_MENU', 'Grupo de menú', TRUE),
    ('CRITERIO_EVALUACION', 'Criterio de evaluación de desempeño', FALSE),
    ('ESTADO_REGISTRO', 'Estado de registro', FALSE),
    ('SUSTENTO', 'Sustento de permiso', FALSE)
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO catalogo_valor (tipo, codigo, nombre, tono, orden, por_defecto, regla, mensaje_regla) VALUES
    ('TIPO_DOCUMENTO', 'DNI', 'DNI', NULL, 10, TRUE, '^[0-9]{8}$', 'El DNI debe tener 8 dígitos'),
    ('TIPO_DOCUMENTO', 'CE', 'Carné de extranjería', NULL, 20, FALSE, '^[A-Z0-9]{8,12}$', 'El carné debe tener entre 8 y 12 caracteres'),
    ('TIPO_DOCUMENTO', 'PASAPORTE', 'Pasaporte', NULL, 30, FALSE, '^[A-Z0-9]{8,12}$', 'El pasaporte debe tener entre 8 y 12 caracteres'),
    ('SEXO', 'M', 'Masculino', NULL, 10, FALSE, NULL, NULL),
    ('SEXO', 'F', 'Femenino', NULL, 20, FALSE, NULL, NULL),
    ('TIPO_CONTRATO', 'PLANILLA', 'Planilla', NULL, 10, TRUE, NULL, NULL),
    ('TIPO_CONTRATO', 'RECIBO_HONORARIOS', 'Recibo por honorarios', NULL, 20, FALSE, NULL, NULL),
    ('TIPO_CONTRATO', 'PRACTICAS', 'Prácticas', NULL, 30, FALSE, NULL, NULL),
    ('ESTADO_EMPLEADO', 'ACTIVO', 'Activo', 'ok', 10, TRUE, NULL, NULL),
    ('ESTADO_EMPLEADO', 'INACTIVO', 'Inactivo', 'danger', 20, FALSE, NULL, NULL),
    ('ESTADO_EMPLEADO', 'CESADO', 'Cesado', 'danger', 30, FALSE, NULL, NULL),
    ('MODALIDAD_CONTRATO', 'COLABORADOR', 'Colaborador', NULL, 10, TRUE, NULL, NULL),
    ('MODALIDAD_CONTRATO', 'PRACTICANTE', 'Practicante', NULL, 20, FALSE, NULL, NULL),
    ('REGIMEN_PENSIONARIO', 'ONP', 'ONP', NULL, 10, TRUE, NULL, NULL),
    ('REGIMEN_PENSIONARIO', 'AFP', 'AFP', NULL, 20, FALSE, NULL, NULL),
    ('REGIMEN_PENSIONARIO', 'NINGUNO', 'Sin régimen', NULL, 30, FALSE, NULL, NULL),
    ('ESTADO_CONTRATO', 'VIGENTE', 'Vigente', 'ok', 10, TRUE, NULL, NULL),
    ('ESTADO_CONTRATO', 'FINALIZADO', 'Finalizado', 'muted', 20, FALSE, NULL, NULL),
    ('ESTADO_CONTRATO', 'ANULADO', 'Anulado', 'danger', 30, FALSE, NULL, NULL),
    ('ESTADO_SOLICITUD', 'PENDIENTE', 'Pendiente', 'warn', 10, TRUE, NULL, NULL),
    ('ESTADO_SOLICITUD', 'APROBADO', 'Aprobado', 'ok', 20, FALSE, NULL, NULL),
    ('ESTADO_SOLICITUD', 'RECHAZADO', 'Rechazado', 'danger', 30, FALSE, NULL, NULL),
    ('ESTADO_SOLICITUD', 'CANCELADO', 'Cancelado', 'danger', 40, FALSE, NULL, NULL),
    ('ESTADO_PASO', 'PENDIENTE', 'Pendiente', 'muted', 10, TRUE, NULL, NULL),
    ('ESTADO_PASO', 'EN_CURSO', 'En curso', 'warn', 20, FALSE, NULL, NULL),
    ('ESTADO_PASO', 'APROBADO', 'Aprobado', 'ok', 30, FALSE, NULL, NULL),
    ('ESTADO_PASO', 'RECHAZADO', 'Rechazado', 'danger', 40, FALSE, NULL, NULL),
    ('ESTADO_PASO', 'OMITIDO', 'Omitido', 'muted', 50, FALSE, NULL, NULL),
    ('ESTADO_PASO', 'CANCELADO', 'Cancelado', 'danger', 60, FALSE, NULL, NULL),
    ('TIPO_MARCACION', 'INGRESO', 'Ingreso', 'info', 10, TRUE, NULL, NULL),
    ('TIPO_MARCACION', 'SALIDA', 'Salida', 'neutral', 20, FALSE, NULL, NULL),
    ('ORIGEN_MARCACION', 'WEB', 'Web', NULL, 10, TRUE, NULL, NULL),
    ('ORIGEN_MARCACION', 'MOVIL', 'Móvil', NULL, 20, FALSE, NULL, NULL),
    ('ORIGEN_MARCACION', 'MANUAL', 'Manual', NULL, 30, FALSE, NULL, NULL),
    ('ORIGEN_MARCACION', 'CORRECCION', 'Corrección', NULL, 40, FALSE, NULL, NULL),
    ('ESTADO_PLANILLA', 'BORRADOR', 'Borrador', 'muted', 10, TRUE, NULL, NULL),
    ('ESTADO_PLANILLA', 'CALCULADA', 'Calculada', 'info', 20, FALSE, NULL, NULL),
    ('ESTADO_PLANILLA', 'CERRADA', 'Cerrada', 'ok', 30, FALSE, NULL, NULL),
    ('ESTADO_PLANILLA', 'ANULADA', 'Anulada', 'danger', 40, FALSE, NULL, NULL),
    ('ESTADO_ASIENTO', 'BORRADOR', 'Borrador', 'muted', 10, FALSE, NULL, NULL),
    ('ESTADO_ASIENTO', 'CONTABILIZADO', 'Contabilizado', 'ok', 20, TRUE, NULL, NULL),
    ('ESTADO_ASIENTO', 'ANULADO', 'Anulado', 'danger', 30, FALSE, NULL, NULL),
    ('ESTADO_EVALUACION', 'BORRADOR', 'Borrador', 'muted', 10, FALSE, NULL, NULL),
    ('ESTADO_EVALUACION', 'CERRADA', 'Cerrada', 'ok', 20, TRUE, NULL, NULL),
    ('ESTADO_CONVOCATORIA', 'ABIERTA', 'Abierta', 'ok', 10, TRUE, NULL, NULL),
    ('ESTADO_CONVOCATORIA', 'CERRADA', 'Cerrada', 'muted', 20, FALSE, NULL, NULL),
    ('ESTADO_CONVOCATORIA', 'CANCELADA', 'Cancelada', 'danger', 30, FALSE, NULL, NULL),
    ('ESTADO_POSTULACION', 'POSTULADO', 'Postulado', 'muted', 10, TRUE, NULL, NULL),
    ('ESTADO_POSTULACION', 'ENTREVISTA', 'Entrevista', 'warn', 20, FALSE, NULL, NULL),
    ('ESTADO_POSTULACION', 'SELECCIONADO', 'Seleccionado', 'info', 30, FALSE, NULL, NULL),
    ('ESTADO_POSTULACION', 'CONTRATADO', 'Contratado', 'ok', 40, FALSE, NULL, NULL),
    ('ESTADO_POSTULACION', 'DESCARTADO', 'Descartado', 'danger', 50, FALSE, NULL, NULL),
    ('TIPO_ORIGEN_FLUJO', 'PERMISO', 'Permiso', NULL, 10, TRUE, NULL, NULL),
    ('TIPO_ORIGEN_FLUJO', 'HORA_EXTRA', 'Horas extras', NULL, 20, FALSE, NULL, NULL),
    ('TIPO_APROBADOR', 'JEFE_INMEDIATO', 'Jefe inmediato', NULL, 10, TRUE, NULL, NULL),
    ('TIPO_APROBADOR', 'ROL', 'Perfil', NULL, 20, FALSE, NULL, NULL),
    ('TIPO_APROBADOR', 'USUARIO', 'Usuario específico', NULL, 30, FALSE, NULL, NULL),
    ('TIPO_REPORTE', 'PERMISOS', 'Permisos', NULL, 10, TRUE, NULL, NULL),
    ('TIPO_REPORTE', 'HORAS_EXTRAS', 'Horas extras', NULL, 20, FALSE, NULL, NULL),
    ('TIPO_REPORTE', 'ASISTENCIA', 'Asistencia', NULL, 30, FALSE, NULL, NULL),
    ('TIPO_REPORTE', 'TRABAJADORES', 'Personal', NULL, 40, FALSE, NULL, NULL),
    ('TIPO_REPORTE', 'USUARIOS', 'Usuarios', NULL, 50, FALSE, NULL, NULL),
    ('TIPO_NOTIFICACION', 'BANDEJA', 'Por aprobar', 'warn', 10, FALSE, NULL, NULL),
    ('TIPO_NOTIFICACION', 'APROBADA', 'Aprobada', 'ok', 20, FALSE, NULL, NULL),
    ('TIPO_NOTIFICACION', 'RECHAZADA', 'Rechazada', 'danger', 30, FALSE, NULL, NULL),
    ('USO_CUENTA', 'SUELDOS', 'Sueldos (debe)', NULL, 10, TRUE, NULL, NULL),
    ('USO_CUENTA', 'ESSALUD_GASTO', 'EsSalud gasto (debe)', NULL, 20, FALSE, NULL, NULL),
    ('USO_CUENTA', 'ONP_POR_PAGAR', 'ONP por pagar', NULL, 30, FALSE, NULL, NULL),
    ('USO_CUENTA', 'AFP_POR_PAGAR', 'AFP por pagar', NULL, 40, FALSE, NULL, NULL),
    ('USO_CUENTA', 'QUINTA_POR_PAGAR', 'Renta de 5ta por pagar', NULL, 50, FALSE, NULL, NULL),
    ('USO_CUENTA', 'ESSALUD_POR_PAGAR', 'EsSalud por pagar', NULL, 60, FALSE, NULL, NULL),
    ('USO_CUENTA', 'REMU_POR_PAGAR', 'Remuneraciones por pagar', NULL, 70, FALSE, NULL, NULL),
    ('USO_CUENTA', 'DESC_AUSENCIAS', 'Descuentos por ausencias', NULL, 80, FALSE, NULL, NULL),
    ('NATURALEZA_CUENTA', 'GASTO', 'Gasto', NULL, 10, TRUE, NULL, NULL),
    ('NATURALEZA_CUENTA', 'PASIVO', 'Pasivo', NULL, 20, FALSE, NULL, NULL),
    ('NATURALEZA_CUENTA', 'ACTIVO', 'Activo', NULL, 30, FALSE, NULL, NULL),
    ('GRUPO_MENU', 'Operación', 'Operación', NULL, 10, TRUE, NULL, NULL),
    ('GRUPO_MENU', 'Administración', 'Administración', NULL, 20, FALSE, NULL, NULL),
    ('GRUPO_MENU', 'Gestión', 'Gestión', NULL, 30, FALSE, NULL, NULL),
    ('GRUPO_MENU', 'Control', 'Control', NULL, 40, FALSE, NULL, NULL),
    ('CRITERIO_EVALUACION', 'PUNTUALIDAD', 'Puntualidad', NULL, 10, FALSE, NULL, NULL),
    ('CRITERIO_EVALUACION', 'CALIDAD', 'Calidad del trabajo', NULL, 20, FALSE, NULL, NULL),
    ('CRITERIO_EVALUACION', 'COOPERACION', 'Cooperación', NULL, 30, FALSE, NULL, NULL),
    ('CRITERIO_EVALUACION', 'INICIATIVA', 'Iniciativa', NULL, 40, FALSE, NULL, NULL),
    ('ESTADO_REGISTRO', 'ACTIVO', 'Activo', 'ok', 10, TRUE, NULL, NULL),
    ('ESTADO_REGISTRO', 'INACTIVO', 'Inactivo', 'danger', 20, FALSE, NULL, NULL),
    ('ESTADO_REGISTRO', 'SISTEMA', 'Sistema', 'neutral', 30, FALSE, NULL, NULL),
    ('SUSTENTO', 'OBLIGATORIO', 'Obligatorio', 'neutral', 10, FALSE, NULL, NULL),
    ('SUSTENTO', 'OPCIONAL', 'Opcional', 'warn', 20, TRUE, NULL, NULL)
ON CONFLICT (tipo, codigo) DO NOTHING;

-- -----------------------------------------------------------------------------
-- 3. AFP con su comisión (reemplaza los parámetros tasa_afp_comision_*)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS afp (
    codigo          VARCHAR(20) PRIMARY KEY,
    nombre          VARCHAR(80) NOT NULL,
    tasa_comision   NUMERIC(7, 5) NOT NULL,
    orden           INTEGER NOT NULL DEFAULT 0,
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_afp_tasa CHECK (tasa_comision >= 0 AND tasa_comision < 1)
);

INSERT INTO afp (codigo, nombre, tasa_comision, orden)
SELECT v.codigo, v.nombre,
       COALESCE((SELECT p.valor::NUMERIC FROM parametro_sistema p WHERE p.clave = v.clave), v.tasa),
       v.orden
FROM (VALUES
    ('HABITAT', 'AFP Habitat', 'tasa_afp_comision_habitat', 0.0147, 10),
    ('INTEGRA', 'AFP Integra', 'tasa_afp_comision_integra', 0.0155, 20),
    ('PRIMA', 'AFP Prima', 'tasa_afp_comision_prima', 0.0160, 30),
    ('PROFUTURO', 'AFP Profuturo', 'tasa_afp_comision_profuturo', 0.0169, 40)
) AS v(codigo, nombre, clave, tasa, orden)
ON CONFLICT (codigo) DO NOTHING;

-- -----------------------------------------------------------------------------
-- 4. Régimen laboral como tabla (factores de beneficios)
-- -----------------------------------------------------------------------------
ALTER TABLE contrato ADD COLUMN IF NOT EXISTS regimen_laboral VARCHAR(20) NOT NULL DEFAULT 'GENERAL';

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'regimen_laboral' AND typtype = 'e') THEN
        ALTER TABLE contrato ALTER COLUMN regimen_laboral DROP DEFAULT;
        ALTER TABLE contrato ALTER COLUMN regimen_laboral TYPE VARCHAR(20) USING regimen_laboral::TEXT;
        ALTER TABLE contrato ALTER COLUMN regimen_laboral SET DEFAULT 'GENERAL';
        DROP TYPE regimen_laboral;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS regimen_laboral (
    codigo                  VARCHAR(20) PRIMARY KEY,
    nombre                  VARCHAR(80) NOT NULL,
    descripcion             VARCHAR(250),
    factor_gratificacion    NUMERIC(5, 4) NOT NULL DEFAULT 1,
    factor_cts              NUMERIC(5, 4) NOT NULL DEFAULT 1,
    aplica_essalud          BOOLEAN NOT NULL DEFAULT TRUE,
    por_defecto             BOOLEAN NOT NULL DEFAULT FALSE,
    orden                   INTEGER NOT NULL DEFAULT 0,
    activo                  BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_regimen_factores CHECK (factor_gratificacion >= 0 AND factor_cts >= 0)
);

INSERT INTO regimen_laboral (codigo, nombre, descripcion, factor_gratificacion, factor_cts, aplica_essalud, por_defecto, orden) VALUES
    ('GENERAL', 'Régimen general', 'D. Leg. 728: gratificación y CTS completas, EsSalud 9 %', 1, 1, TRUE, TRUE, 10),
    ('MYPE_PEQUENA', 'Pequeña empresa', 'Ley 32353: media gratificación, medio CTS, EsSalud 9 %', 0.5, 0.5, TRUE, FALSE, 20),
    ('MYPE_MICRO', 'Microempresa', 'Ley 32353: sin gratificación ni CTS, SIS en lugar de EsSalud', 0, 0, FALSE, FALSE, 30)
ON CONFLICT (codigo) DO NOTHING;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_regimen_laboral') THEN
        ALTER TABLE contrato ADD CONSTRAINT fk_contrato_regimen_laboral
            FOREIGN KEY (regimen_laboral) REFERENCES regimen_laboral (codigo);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_afp') THEN
        ALTER TABLE contrato ADD CONSTRAINT fk_contrato_afp
            FOREIGN KEY (afp_nombre) REFERENCES afp (codigo);
    END IF;
END $$;

ALTER TABLE planilla_detalle
    ADD COLUMN IF NOT EXISTS gratificacion_proyectada NUMERIC(12, 2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cts_proyectado NUMERIC(12, 2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS regimen_laboral VARCHAR(20);

-- -----------------------------------------------------------------------------
-- 5. Escala de renta de 5ta categoría (límite superior acumulado en UIT)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tramo_renta_quinta (
    id_tramo        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden           INTEGER NOT NULL,
    hasta_uit       NUMERIC(8, 2),
    tasa            NUMERIC(6, 4) NOT NULL,
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_tramo_quinta_orden UNIQUE (orden),
    CONSTRAINT ck_tramo_quinta_tasa CHECK (tasa >= 0 AND tasa < 1)
);

COMMENT ON COLUMN tramo_renta_quinta.hasta_uit IS 'Límite superior acumulado del tramo en UIT. NULL = sin límite (último tramo).';

INSERT INTO tramo_renta_quinta (orden, hasta_uit, tasa) VALUES
    (10, 5, 0.08),
    (20, 20, 0.14),
    (30, 35, 0.17),
    (40, 45, 0.20),
    (50, NULL, 0.30)
ON CONFLICT (orden) DO NOTHING;

-- -----------------------------------------------------------------------------
-- 6. Marcas de sistema y suplencias (sustituyen códigos fijos en el código)
-- -----------------------------------------------------------------------------
ALTER TABLE rol ADD COLUMN IF NOT EXISTS es_sistema BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE rol ADD COLUMN IF NOT EXISTS id_rol_suplente INTEGER REFERENCES rol (id_rol);
ALTER TABLE menu_item ADD COLUMN IF NOT EXISTS es_sistema BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE tipo_permiso ADD COLUMN IF NOT EXISTS es_vacaciones BOOLEAN NOT NULL DEFAULT FALSE;

COMMENT ON COLUMN rol.es_sistema IS 'Perfil protegido: no cambia de código, no se desactiva y conserva los menús de sistema.';
COMMENT ON COLUMN rol.id_rol_suplente IS 'Perfil que también puede decidir los pasos asignados a este perfil.';
COMMENT ON COLUMN menu_item.es_sistema IS 'Opción protegida: no se elimina ni desactiva y siempre queda en los perfiles de sistema.';
COMMENT ON COLUMN tipo_permiso.es_vacaciones IS 'Consume saldo de vacaciones y no descuenta en planilla.';

-- -----------------------------------------------------------------------------
-- 7. Permisos funcionales nuevos (se asignan solo la primera vez que se crean)
-- -----------------------------------------------------------------------------
WITH nuevos AS (
    INSERT INTO permiso_funcional (codigo, nombre, modulo) VALUES
        ('CONTRATO_GESTIONAR', 'Gestionar contratos', 'CONTRATOS'),
        ('PLANILLA_GESTIONAR', 'Calcular, cerrar y exportar planillas', 'PLANILLAS'),
        ('CONTABILIDAD_CONSULTAR', 'Consultar asientos contables', 'CONTABILIDAD'),
        ('MAESTRO_GESTIONAR', 'Gestionar maestros, catálogos y parámetros', 'MAESTROS'),
        ('RECLUTAMIENTO_GESTIONAR', 'Gestionar convocatorias y postulantes', 'RECLUTAMIENTO'),
        ('USUARIO_CONSULTAR', 'Consultar cuentas de usuario', 'USUARIOS'),
        ('ROL_GESTIONAR', 'Gestionar perfiles y permisos', 'SEGURIDAD'),
        ('MENU_GESTIONAR', 'Gestionar opciones de menú', 'SEGURIDAD'),
        ('DESEMPENO_REGISTRAR', 'Registrar evaluaciones de desempeño', 'DESEMPENO'),
        ('ALCANCE_TOTAL', 'Ver y gestionar información de todo el personal', 'ALCANCE'),
        ('ALCANCE_ORGANIZACION', 'Consultar información de todo el personal', 'ALCANCE'),
        ('ALCANCE_EQUIPO', 'Gestionar a su equipo directo', 'ALCANCE')
    ON CONFLICT (codigo) DO NOTHING
    RETURNING id_permiso, codigo
)
INSERT INTO rol_permiso (id_rol, id_permiso)
SELECT r.id_rol, n.id_permiso
FROM nuevos n
JOIN (VALUES
    ('ADMIN', 'CONTRATO_GESTIONAR'), ('ADMIN', 'PLANILLA_GESTIONAR'), ('ADMIN', 'CONTABILIDAD_CONSULTAR'),
    ('ADMIN', 'MAESTRO_GESTIONAR'), ('ADMIN', 'RECLUTAMIENTO_GESTIONAR'), ('ADMIN', 'USUARIO_CONSULTAR'),
    ('ADMIN', 'ROL_GESTIONAR'), ('ADMIN', 'MENU_GESTIONAR'), ('ADMIN', 'DESEMPENO_REGISTRAR'),
    ('ADMIN', 'ALCANCE_TOTAL'),
    ('RRHH', 'CONTRATO_GESTIONAR'), ('RRHH', 'PLANILLA_GESTIONAR'), ('RRHH', 'CONTABILIDAD_CONSULTAR'),
    ('RRHH', 'MAESTRO_GESTIONAR'), ('RRHH', 'RECLUTAMIENTO_GESTIONAR'), ('RRHH', 'USUARIO_CONSULTAR'),
    ('RRHH', 'DESEMPENO_REGISTRAR'), ('RRHH', 'ALCANCE_TOTAL'),
    ('GERENCIA', 'DESEMPENO_REGISTRAR'), ('GERENCIA', 'ALCANCE_ORGANIZACION'),
    ('JEFE', 'DESEMPENO_REGISTRAR'), ('JEFE', 'ALCANCE_EQUIPO')
) AS m(rol, permiso) ON m.permiso = n.codigo
JOIN rol r ON r.codigo = m.rol
ON CONFLICT DO NOTHING;

-- -----------------------------------------------------------------------------
-- 8. Ajustes de una sola vez (no se repiten para no pisar cambios del usuario)
-- -----------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM script_aplicado WHERE codigo = '06_configuracion_dinamica') THEN
        UPDATE rol SET es_sistema = TRUE WHERE codigo = 'ADMIN';
        UPDATE menu_item SET es_sistema = TRUE WHERE codigo IN ('MENU', 'ROLES');
        UPDATE rol g SET id_rol_suplente = a.id_rol
        FROM rol a
        WHERE g.codigo = 'GERENCIA' AND a.codigo = 'ADMIN' AND g.id_rol_suplente IS NULL;
        UPDATE tipo_permiso SET es_vacaciones = TRUE WHERE codigo = 'VACACIONES';

        UPDATE parametro_sistema SET ambito = 'PUBLICO'
        WHERE clave IN ('app_nombre', 'empresa_razon_social', 'empresa_nombre_comercial', 'empresa_siglas',
                        'empresa_ruc', 'empresa_direccion', 'zona_horaria', 'locale', 'moneda_codigo', 'moneda_simbolo');
        UPDATE parametro_sistema SET ambito = 'PRIVADO' WHERE clave = 'password_inicial';

        DELETE FROM parametro_sistema
        WHERE clave IN ('tasa_afp_comision_habitat', 'tasa_afp_comision_integra',
                        'tasa_afp_comision_prima', 'tasa_afp_comision_profuturo',
                        'rmv_2026_10_01', 'rmv_2027_q1', 'uit_2025', 'uit_2026',
                        'ram_2026_q1', 'ram_2026_q2', 'ram_2026_q3', 'tasa_hora_extra');

        INSERT INTO script_aplicado (codigo) VALUES ('06_configuracion_dinamica');
    END IF;
END $$;

-- -----------------------------------------------------------------------------
-- 9. Reglas que pasaron a parámetros o catálogos: se relajan los CHECK fijos
-- -----------------------------------------------------------------------------
ALTER TABLE empleado DROP CONSTRAINT IF EXISTS ck_empleado_dni;

ALTER TABLE solicitud_hora_extra DROP CONSTRAINT IF EXISTS ck_hora_extra_cantidad;
ALTER TABLE solicitud_hora_extra DROP CONSTRAINT IF EXISTS ck_hora_extra_positiva;
ALTER TABLE solicitud_hora_extra ADD CONSTRAINT ck_hora_extra_positiva CHECK (cantidad_horas > 0);

ALTER TABLE solicitud_hora_extra DROP CONSTRAINT IF EXISTS ck_hora_extra_motivo;
ALTER TABLE solicitud_hora_extra ADD CONSTRAINT ck_hora_extra_motivo CHECK (length(btrim(motivo)) > 0);
ALTER TABLE solicitud_permiso DROP CONSTRAINT IF EXISTS ck_permiso_motivo;
ALTER TABLE solicitud_permiso ADD CONSTRAINT ck_permiso_motivo CHECK (length(btrim(motivo)) > 0);

ALTER TABLE evaluacion_desempeno DROP CONSTRAINT IF EXISTS ck_eval_puntajes;
ALTER TABLE evaluacion_desempeno ADD CONSTRAINT ck_eval_puntajes CHECK (
    puntualidad >= 0 AND calidad >= 0 AND cooperacion >= 0 AND iniciativa >= 0);

COMMENT ON TABLE contrato IS
    'Vínculo laboral: modalidad, régimen laboral y pensionario, horario y fechas para acumular vacaciones.';

-- El perfil suplente también puede decidir el paso.
CREATE OR REPLACE FUNCTION fn_usuario_puede_decidir_paso(
    p_id_paso INTEGER,
    p_id_usuario INTEGER
)
RETURNS BOOLEAN AS $$
DECLARE
    v_paso solicitud_paso_aprobacion%ROWTYPE;
    v_id_rol INTEGER;
BEGIN
    SELECT * INTO v_paso
    FROM solicitud_paso_aprobacion
    WHERE id_paso_solicitud = p_id_paso;

    IF NOT FOUND OR v_paso.estado <> 'EN_CURSO' THEN
        RETURN FALSE;
    END IF;

    SELECT id_rol INTO v_id_rol
    FROM usuario
    WHERE id_usuario = p_id_usuario
      AND activo;

    IF v_id_rol IS NULL THEN
        RETURN FALSE;
    END IF;

    IF v_paso.tipo_aprobador IN ('JEFE_INMEDIATO', 'USUARIO') THEN
        RETURN v_paso.id_usuario_asignado = p_id_usuario;
    END IF;

    RETURN v_paso.id_rol = v_id_rol
        OR EXISTS (SELECT 1 FROM rol r WHERE r.id_rol = v_paso.id_rol AND r.id_rol_suplente = v_id_rol);
END;
$$ LANGUAGE plpgsql STABLE;

-- Topes de horas extras sin valores por defecto: se exige el parámetro.
CREATE OR REPLACE FUNCTION fn_validar_hora_extra()
RETURNS TRIGGER AS $$
DECLARE
    v_max_diarias NUMERIC;
    v_max_semanales NUMERIC;
    v_acumulado_dia NUMERIC;
    v_acumulado_semana NUMERIC;
BEGIN
    SELECT valor::NUMERIC INTO v_max_diarias
    FROM parametro_sistema WHERE clave = 'max_horas_extras_diarias';

    SELECT valor::NUMERIC INTO v_max_semanales
    FROM parametro_sistema WHERE clave = 'max_horas_extras_semanales';

    IF v_max_diarias IS NULL OR v_max_semanales IS NULL THEN
        RAISE EXCEPTION 'Configure los parámetros max_horas_extras_diarias y max_horas_extras_semanales.';
    END IF;

    SELECT COALESCE(SUM(cantidad_horas), 0) INTO v_acumulado_dia
    FROM solicitud_hora_extra
    WHERE id_empleado = NEW.id_empleado
      AND fecha = NEW.fecha
      AND estado IN ('PENDIENTE', 'APROBADO')
      AND (TG_OP = 'INSERT' OR id_solicitud_hora_extra <> NEW.id_solicitud_hora_extra);

    IF v_acumulado_dia + NEW.cantidad_horas > v_max_diarias THEN
        RAISE EXCEPTION 'La cantidad de horas extras del día supera el máximo permitido (%).', v_max_diarias;
    END IF;

    SELECT COALESCE(SUM(cantidad_horas), 0) INTO v_acumulado_semana
    FROM solicitud_hora_extra
    WHERE id_empleado = NEW.id_empleado
      AND fecha >= date_trunc('week', NEW.fecha)::date
      AND fecha < date_trunc('week', NEW.fecha)::date + 7
      AND estado IN ('PENDIENTE', 'APROBADO')
      AND (TG_OP = 'INSERT' OR id_solicitud_hora_extra <> NEW.id_solicitud_hora_extra);

    IF v_acumulado_semana + NEW.cantidad_horas > v_max_semanales THEN
        RAISE EXCEPTION 'La cantidad de horas extras de la semana supera el máximo permitido (%).', v_max_semanales;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
