INSERT INTO horario_laboral (nombre, hora_ingreso, hora_salida, minutos_refrigerio)
SELECT 'Jornada de prácticas', TIME '09:00', TIME '14:00', 0
WHERE NOT EXISTS (SELECT 1 FROM horario_laboral WHERE nombre = 'Jornada de prácticas');

INSERT INTO parametro_sistema (clave, valor, descripcion)
VALUES (
    'dias_vacaciones_mensuales',
    '1.5',
    'Días de vacaciones que acumula un trabajador por cada mes completo, sea colaborador o practicante'
)
ON CONFLICT (clave) DO NOTHING;

CREATE TABLE IF NOT EXISTS contrato (
    id_contrato         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo              VARCHAR(20) NOT NULL,
    id_empleado         INTEGER NOT NULL REFERENCES empleado (id_empleado),
    modalidad           modalidad_contrato NOT NULL,
    id_horario          INTEGER NOT NULL REFERENCES horario_laboral (id_horario),
    fecha_inicio        DATE NOT NULL,
    fecha_fin           DATE,
    estado              estado_contrato NOT NULL DEFAULT 'VIGENTE',
    observaciones       VARCHAR(300),
    fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_contrato_codigo UNIQUE (codigo),
    CONSTRAINT ck_contrato_fechas CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio),
    CONSTRAINT ck_contrato_practicas_fin CHECK (
        modalidad <> 'PRACTICANTE' OR fecha_fin IS NOT NULL
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_contrato_empleado_vigente
    ON contrato (id_empleado)
    WHERE estado = 'VIGENTE';

COMMENT ON TABLE contrato IS 'Vínculo laboral vigente: colaborador o practicante, con horario y fechas para acumular vacaciones (1.5 días/mes).';

INSERT INTO contrato (codigo, id_empleado, modalidad, id_horario, fecha_inicio, estado, observaciones)
SELECT v.codigo, e.id_empleado, v.modalidad::modalidad_contrato, e.id_horario, e.fecha_ingreso, 'VIGENTE',
       'Contrato inicial de demostración'
FROM (VALUES
    ('CTR-001', 'AND-001', 'COLABORADOR'),
    ('CTR-002', 'AND-002', 'COLABORADOR'),
    ('CTR-003', 'AND-003', 'COLABORADOR')
) AS v(codigo, codigo_empleado, modalidad)
JOIN empleado e ON e.codigo_empleado = v.codigo_empleado
WHERE NOT EXISTS (SELECT 1 FROM contrato c WHERE c.codigo = v.codigo);

INSERT INTO menu_item (codigo, etiqueta, ruta, icono, grupo, descripcion, orden)
SELECT 'CONTRATOS', 'Contratos', '/contratos', 'FileText', 'Administración',
       'Modalidad, horario y vigencia del vínculo laboral.', 85
WHERE NOT EXISTS (SELECT 1 FROM menu_item WHERE codigo = 'CONTRATOS');

INSERT INTO menu_rol (id_menu, id_rol)
SELECT m.id_menu, r.id_rol
FROM menu_item m
JOIN rol r ON r.codigo IN ('ADMIN', 'RRHH')
WHERE m.codigo = 'CONTRATOS'
  AND NOT EXISTS (SELECT 1 FROM menu_rol x WHERE x.id_menu = m.id_menu AND x.id_rol = r.id_rol);
