ALTER TABLE contrato
    ADD COLUMN IF NOT EXISTS remuneracion_basica NUMERIC(12, 2) NOT NULL DEFAULT 0;

UPDATE contrato SET remuneracion_basica = 4200 WHERE codigo = 'CTR-001' AND remuneracion_basica = 0;
UPDATE contrato SET remuneracion_basica = 3800 WHERE codigo = 'CTR-002' AND remuneracion_basica = 0;
UPDATE contrato SET remuneracion_basica = 3200 WHERE codigo = 'CTR-003' AND remuneracion_basica = 0;

INSERT INTO parametro_sistema (clave, valor, descripcion)
VALUES
    ('tasa_hora_extra', '1.25', 'Multiplicador de la hora extra sobre el valor hora (sueldo / 240)'),
    ('tasa_essalud', '0.09', 'Aporte de EsSalud a cargo del empleador'),
    ('tasa_onp', '0.13', 'Descuento ONP del colaborador (modelo simplificado)'),
    ('horas_mensuales_base', '240', 'Horas mensuales para valorizar la hora ordinaria')
ON CONFLICT (clave) DO NOTHING;

CREATE TABLE IF NOT EXISTS planilla (
    id_planilla         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anio                INTEGER NOT NULL,
    mes                 INTEGER NOT NULL,
    estado              estado_planilla NOT NULL DEFAULT 'BORRADOR',
    total_bruto         NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total_descuentos    NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total_aportes       NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total_neto          NUMERIC(12, 2) NOT NULL DEFAULT 0,
    observaciones       VARCHAR(400),
    fecha_calculo       TIMESTAMPTZ,
    fecha_cierre        TIMESTAMPTZ,
    fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_planilla_periodo UNIQUE (anio, mes),
    CONSTRAINT ck_planilla_mes CHECK (mes BETWEEN 1 AND 12)
);

CREATE TABLE IF NOT EXISTS planilla_detalle (
    id_detalle          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_planilla         INTEGER NOT NULL REFERENCES planilla (id_planilla) ON DELETE CASCADE,
    id_empleado         INTEGER NOT NULL REFERENCES empleado (id_empleado),
    id_contrato         INTEGER REFERENCES contrato (id_contrato),
    modalidad           VARCHAR(20),
    remuneracion_basica NUMERIC(12, 2) NOT NULL DEFAULT 0,
    horas_extras        NUMERIC(8, 2) NOT NULL DEFAULT 0,
    monto_horas_extras  NUMERIC(12, 2) NOT NULL DEFAULT 0,
    dias_no_laborados   NUMERIC(6, 2) NOT NULL DEFAULT 0,
    descuento_ausencias NUMERIC(12, 2) NOT NULL DEFAULT 0,
    onp                 NUMERIC(12, 2) NOT NULL DEFAULT 0,
    essalud             NUMERIC(12, 2) NOT NULL DEFAULT 0,
    bruto               NUMERIC(12, 2) NOT NULL DEFAULT 0,
    neto                NUMERIC(12, 2) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS asiento_contable (
    id_asiento      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(30) NOT NULL,
    id_planilla     INTEGER REFERENCES planilla (id_planilla),
    fecha           DATE NOT NULL,
    glosa           VARCHAR(200) NOT NULL,
    estado          estado_asiento NOT NULL DEFAULT 'CONTABILIZADO',
    total_debe      NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total_haber     NUMERIC(12, 2) NOT NULL DEFAULT 0,
    fecha_creacion  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_asiento_codigo UNIQUE (codigo)
);

CREATE TABLE IF NOT EXISTS asiento_linea (
    id_linea        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_asiento      INTEGER NOT NULL REFERENCES asiento_contable (id_asiento) ON DELETE CASCADE,
    cuenta          VARCHAR(20) NOT NULL,
    nombre_cuenta   VARCHAR(80) NOT NULL,
    debe            NUMERIC(12, 2) NOT NULL DEFAULT 0,
    haber           NUMERIC(12, 2) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS evaluacion_desempeno (
    id_evaluacion   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empleado     INTEGER NOT NULL REFERENCES empleado (id_empleado),
    id_evaluador    INTEGER REFERENCES usuario (id_usuario),
    periodo         VARCHAR(20) NOT NULL,
    fecha           DATE NOT NULL DEFAULT CURRENT_DATE,
    puntualidad     INTEGER NOT NULL,
    calidad         INTEGER NOT NULL,
    cooperacion     INTEGER NOT NULL,
    iniciativa      INTEGER NOT NULL,
    promedio        NUMERIC(4, 2) NOT NULL,
    comentario      VARCHAR(400),
    estado          estado_evaluacion NOT NULL DEFAULT 'CERRADA',
    fecha_creacion  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_eval_puntajes CHECK (
        puntualidad BETWEEN 1 AND 5
        AND calidad BETWEEN 1 AND 5
        AND cooperacion BETWEEN 1 AND 5
        AND iniciativa BETWEEN 1 AND 5
    )
);

CREATE TABLE IF NOT EXISTS convocatoria (
    id_convocatoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(20) NOT NULL,
    puesto          VARCHAR(120) NOT NULL,
    id_area         INTEGER REFERENCES area (id_area),
    vacantes        INTEGER NOT NULL DEFAULT 1,
    fecha_inicio    DATE NOT NULL,
    fecha_fin       DATE,
    descripcion     VARCHAR(400),
    estado          estado_convocatoria NOT NULL DEFAULT 'ABIERTA',
    fecha_creacion  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_convocatoria_codigo UNIQUE (codigo)
);

CREATE TABLE IF NOT EXISTS postulacion (
    id_postulacion  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_convocatoria INTEGER NOT NULL REFERENCES convocatoria (id_convocatoria) ON DELETE CASCADE,
    nombres         VARCHAR(80) NOT NULL,
    apellidos       VARCHAR(80) NOT NULL,
    documento       VARCHAR(20) NOT NULL,
    correo          VARCHAR(120),
    telefono        VARCHAR(20),
    puntaje         INTEGER,
    estado          estado_postulacion NOT NULL DEFAULT 'POSTULADO',
    observacion     VARCHAR(400),
    fecha_creacion  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO menu_item (codigo, etiqueta, ruta, icono, grupo, descripcion, orden)
SELECT v.codigo, v.etiqueta, v.ruta, v.icono, v.grupo, v.descripcion, v.orden
FROM (VALUES
    ('PLANILLAS', 'Planillas', '/planillas', 'Wallet', 'Gestión', 'Cálculo mensual de remuneraciones y boletas.', 102),
    ('CONTABILIDAD', 'Contabilidad', '/contabilidad', 'BookOpen', 'Gestión', 'Asientos generados al cerrar la planilla.', 104),
    ('DESEMPENO', 'Desempeño', '/desempeno', 'Star', 'Gestión', 'Evaluación periódica del colaborador.', 106),
    ('RECLUTAMIENTO', 'Reclutamiento', '/reclutamiento', 'UserPlus', 'Gestión', 'Convocatorias y seguimiento de postulantes.', 108)
) AS v(codigo, etiqueta, ruta, icono, grupo, descripcion, orden)
WHERE NOT EXISTS (SELECT 1 FROM menu_item m WHERE m.codigo = v.codigo);

INSERT INTO menu_rol (id_menu, id_rol)
SELECT m.id_menu, r.id_rol
FROM menu_item m
JOIN rol r ON r.codigo IN ('ADMIN', 'RRHH')
WHERE m.codigo IN ('PLANILLAS', 'CONTABILIDAD', 'DESEMPENO', 'RECLUTAMIENTO')
  AND NOT EXISTS (SELECT 1 FROM menu_rol x WHERE x.id_menu = m.id_menu AND x.id_rol = r.id_rol);

INSERT INTO menu_rol (id_menu, id_rol)
SELECT m.id_menu, r.id_rol
FROM menu_item m
JOIN rol r ON r.codigo = 'APROBADOR'
WHERE m.codigo = 'DESEMPENO'
  AND NOT EXISTS (SELECT 1 FROM menu_rol x WHERE x.id_menu = m.id_menu AND x.id_rol = r.id_rol);

INSERT INTO convocatoria (codigo, puesto, id_area, vacantes, fecha_inicio, fecha_fin, descripcion, estado)
SELECT 'CONV-001', 'Analista contable junior', a.id_area, 1, CURRENT_DATE - 10, CURRENT_DATE + 20,
       'Convocatoria de demostración para el área contable.', 'ABIERTA'
FROM area a
WHERE a.nombre ILIKE '%contab%'
  AND NOT EXISTS (SELECT 1 FROM convocatoria c WHERE c.codigo = 'CONV-001')
LIMIT 1;

CREATE TABLE IF NOT EXISTS cuenta_contable (
    id_cuenta       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(20) NOT NULL,
    nombre          VARCHAR(80) NOT NULL,
    uso             VARCHAR(40) NOT NULL,
    naturaleza      VARCHAR(12) NOT NULL DEFAULT 'GASTO',
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_cuenta_codigo UNIQUE (codigo),
    CONSTRAINT uq_cuenta_uso UNIQUE (uso)
);

INSERT INTO cuenta_contable (codigo, nombre, uso, naturaleza)
SELECT v.codigo, v.nombre, v.uso, v.naturaleza
FROM (VALUES
    ('6211', 'Sueldos y salarios', 'SUELDOS', 'GASTO'),
    ('6271', 'EsSalud', 'ESSALUD_GASTO', 'GASTO'),
    ('4031', 'ONP por pagar', 'ONP_POR_PAGAR', 'PASIVO'),
    ('4032', 'EsSalud por pagar', 'ESSALUD_POR_PAGAR', 'PASIVO'),
    ('4111', 'Remuneraciones por pagar', 'REMU_POR_PAGAR', 'PASIVO'),
    ('4699', 'Descuentos por ausencias', 'DESC_AUSENCIAS', 'PASIVO')
) AS v(codigo, nombre, uso, naturaleza)
WHERE NOT EXISTS (SELECT 1 FROM cuenta_contable c WHERE c.uso = v.uso);

INSERT INTO menu_item (codigo, etiqueta, ruta, icono, grupo, descripcion, orden)
SELECT 'MAESTROS', 'Maestros', '/maestros', 'Library', 'Administración',
       'Áreas, cargos, horarios, tipos de permiso, parámetros y plan de cuentas.', 88
WHERE NOT EXISTS (SELECT 1 FROM menu_item m WHERE m.codigo = 'MAESTROS');

INSERT INTO menu_rol (id_menu, id_rol)
SELECT m.id_menu, r.id_rol
FROM menu_item m
JOIN rol r ON r.codigo IN ('ADMIN', 'RRHH')
WHERE m.codigo = 'MAESTROS'
  AND NOT EXISTS (SELECT 1 FROM menu_rol x WHERE x.id_menu = m.id_menu AND x.id_rol = r.id_rol);
